hyperledger/indy-sdk

- tests/ledger.rs
Ignore the test to avoid pool instability.
> Ignore sovrin_submit_node_request_works_for_new_steward test

- build.rs
Copy of libzmq-pw.dll to output directory on windows instead of libzmq.dll
> Bugfixes for libzmq-pw on windows

- wrappers/java/src/main/java/org/hyperledger/indy/sdk/pool/Pool.java
Simple change to use correct underlying function call.
> Java wrapper Pool.closePoolLedger method did not use correct C-callable sdk function

- wrappers/java/src/main/java/org/hyperledger/indy/sdk/anoncreds/Anoncreds.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/anoncreds/AnoncredsIntegrationTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/anoncreds/ProverCreateAndStoreClaimReqTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/anoncreds/ProverStoreClaimTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/demo/AnoncredsDemoTest.java
The proverCreateClaimReq() method name did not match the underlying SDK function name indy_prover_create_and_store_claim_req.
> Java method name did not match the SDK function.

- wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibIndy.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/IndyIntegrationTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/utils/InitHelper.java
I think 9ad2cb6eff85589666664e6717456cadca7ffb42 added Windows support in `wrappers/java/src/test/java/org/hyperledger/indy/sdk/utils/InitHelper.java` but broke Linux. I propose this change to add a more platform-independent way to load the library.
> Java Wrapper: Platform-independent way to init libindy

- wrappers/java/src/main/java/org/hyperledger/indy/sdk/wallet/Wallet.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/wallet/WalletTypeInmem.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/wallet/RegisterWalletTypeTest.java
This fixes a number of issues I have discussed with @srottem, e.g.:
- Fixed a bug with unmanaged memory allocation in Java
- Using UTF-8 for strings passed from Java to libindy (https://jira.hyperledger.org/browse/IS-254)
- WalletTypeInmem: Return WalletNotFoundError if a value is not found in the wallet.
> Fix inmem wallet crash

- .gitignore
- Jenkinsfile
- ci/amazon.dockerfile
- ci/ubuntu.dockerfile
- libindy/Cargo.lock
- Add latest Cargo.lock to VCS.
- Remove 'cargo update' command from pipeline.
- Update rust compiler version in pipeline.
> Use fixed dependencies versions to determine build.

- wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibIndy.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/signus/Signus.java
@Artemkaaas I agree the approach with `byte[]` and `Pointer` is correct, this here is just a small patch for variable names.
> Java wrapper: variable names consistent with libindy API

- doc/ubuntu-build.md
Corrected errors in 2 lines.  The instructions said to checkout instead of cloning a git repo, and they put the user in the wrong directory before 'cargo build'
> Update ubuntu-build.md to correct errors in build instructions

- samples/python/src/utils.py
- wrappers/python/indy/agent.py
- wrappers/python/indy/error.py
- wrappers/python/tests/agent/conftest.py
- wrappers/python/tests/anoncreds/conftest.py
- wrappers/python/tests/conftest.py
- wrappers/python/tests/ledger/test_build_nym_request.py
- Provided compatibility of libindy python wrapper with Python 3.5 (previously Python 3.6+ was required) since Python 3.5 is the target platform for indy-node.
- Fixed a bug in pool_genesis_txn_file fixture.
- Fixed a bug in save_pool_genesis_txn_file function.
- Removed Python 3.6 from CI scripts and dockerfiles.
> Made python wrapper compatible with Python 3.5

- libindy/tests/crypto.rs
The removed lines break the test when pool is not running.
Signed-off-by: Lovesh <lovesh.harchandani@evernym.com>
> remove unneccessary line of code

- libindy/src/services/wallet/iterator.rs
- libindy/src/services/wallet/wallet.rs
Instead of cloning keys, now they are accessed via reference counted smart pointer
> keys are now accessed via shared pointer instead of cloned

- libindy/src/api/wallet.rs
The "credentials" parameter to the wallet functions suffered from an unfortunate semantic overload, since "credential" has a very specific meaning with respect to anoncreds and ZKPs. I thought it might improve clarity to call it "credentials_json" instead, to make it clear that we're not expecting a CL-signed anoncreds-style credential, but rather some json that provides credentials for the storage.
> Rename 'credentials' param for clarity

- cli/src/commands/pool.rs
Signed-off-by: Corin Kochenower <corin.kochenower@evernym.com>
> Cleanup of pool connection should say "disconnected"

- CHANGELOG.md
- Specs/libindy-objc/1.6.6/libindy-objc.podspec.json
- Specs/libindy/1.6.6/libindy.podspec.json
- cli/Cargo.lock
- cli/Cargo.toml
- cli/debian/changelog
- libindy/Cargo.lock
- libindy/Cargo.toml
- libindy/android.build.sh
- libindy/debian/changelog
- libnullpay/Cargo.lock
- libnullpay/Cargo.toml
- libnullpay/debian/changelog
- wrappers/java/pom.xml
- wrappers/nodejs/package.json
- wrappers/python/setup.py
There was a bug in yesterdays PR where the aar building was successfully happening on mac but not on linux. This PR is a fix to the rustflag changes raised yesterday. 
Signed-off-by: Mohammad Abdul Sami <faisal00813@gmail.com>
> Added rust flags for all architrcutures

- cli/Cargo.lock
- cli/Cargo.toml
- cli/src/main.rs
- cli/src/utils/term.rs
* Initialize ansi_term from the very beginning
* Check that stdout is terminal in printing macros and disable colors otherwise
> CLI color-related bugfixes

- libindy/tests/ledger.rs
> Corrected `get_response_metadata_works_for_get_txn_request` libindy test

- libindy/include/indy_mod.h
- wrappers/nodejs/README.md
- wrappers/nodejs/src/IndyError.js
- wrappers/nodejs/src/index.js
- wrappers/nodejs/src/indy.cc
- wrappers/nodejs/src/indyBinding.js
- wrappers/nodejs/test/index.js
For both async and sync errors, it calls `indy_get_current_error` and attaches the additional data to the IndyError object.
> Nodejs wrapper - indy_get_current_error

- vcx/libvcx/src/utils/logger.rs
fixes problem where android won't compile because of a moved variable by using the var as a reference
> Fix broken android build

- wrappers/nodejs/README.md
Updating the docs according to the test in `indy-sdk/wrappers/nodejs/test/anoncreds.js`. It says `t.is(proof['requested_proof']['revealed_attrs']['attr1_referent']['raw'], 'Alex')`.
> Rename proof attirubte in Node.js wrapper docs

- libindy/tests/interaction.rs
This version removes a lot of the code repetition. It demonstrates the actions and responsibilities of the parties in exact way they take part in anonymous credential algorithms. The clarity of the test algorithm is improved substantially, so the addition of new tests to the suite should be easy.
The test suite uses new objects : Issuer, Prover and Verifier. Their implementations are self-containing: the corresponding objects hold attributes, which are in the local scope of a party only. The interface methods use minimum of parameters, which are supposed to be exchanged between parties in the network protocol.
The small improvement has been added to the Prover's make_proof() algorithm: it checks whether the proof request contains predicates and acts accordingly.
*** It could make sense to …
> Refactor the interaction test

- docs/how-tos/write-did-and-query-verkey/rust/src/step2.rs
- docs/how-tos/write-did-and-query-verkey/rust/src/step3.rs
- docs/how-tos/write-did-and-query-verkey/rust/src/step4.rs
- docs/how-tos/write-did-and-query-verkey/rust/src/step5.rs
- docs/how-tos/write-did-and-query-verkey/rust/src/template.rs
- docs/how-tos/write-did-and-query-verkey/rust/src/write-did-and-query-verkey.rs
[IS-1185] Rust how-to "write-did-and-query-verkey" does not compile
Summary:
The indy crate is called `indyrs` and not `indy`.
The 'use indy::' statements were incorrect.
Possiblity of SIGILL or other issues if wait() is not called on certain operations. For example: `set_protocol_version(PROTOCOL_VERSION).unwrap()`
Should be: `set_protocol_version(PROTOCOL_VERSION).wait().unwrap()`
> Update Rust how-to write-did-and-query-verkey

- vcx/wrappers/python3/vcx/logging.py
- wrappers/python/indy/libindy.py
PR for IS-1168.
python `logging` use WARN as a default value for log functions. 
So, correspondent Libindy and Libvcx records appeared in a script output.
> Use CRITICAL as default log level for python wrappers

- libindy/src/services/anoncreds/prover.rs
Enables indy_prover_search_credentials_for_proof_req to allow restrictions to be an empty vector 
> Enables indy_prover_search_credentials_for_proof_req to allow restrictions to be an empty vector 

- vcx/dummy-cloud-agent/src/actors/agent.rs
- vcx/dummy-cloud-agent/src/domain/a2a.rs
- vcx/libvcx/src/messages/agent_utils.rs
- vcx/libvcx/src/messages/mod.rs
Connect.me would fail when trying to update the communication method `UPDATE_COM_METHOD` because the message type was `CREATE_AGENT`. 
All references to UpdateConnectionMethod is changed to UpdateComMethod.
> changes A2AMessageV1::UpdateConnectionMethod to UpdateComMethod

- vcx/wrappers/node/src/api/issuer-credential.ts
"price" should be shown as a string in the inline documentation because the function will only accept a string.
> Inline Documentation Fix

- libindy/src/utils/sequence.rs
- libindy/tests/utils/callback.rs
- wrappers/rust/src/utils/sequence.rs
ATOMIC_USIZE_INIT is deprecated in rustc 1.34.0
> ATOMIC_USIZE_INIT is deprecated

- vcx/libvcx/src/api/credential.rs
- vcx/libvcx/src/api/issuer_credential.rs
- vcx/libvcx/src/api/wallet.rs
- vcx/libvcx/src/credential.rs
- vcx/libvcx/src/disclosed_proof.rs
- vcx/libvcx/src/issuer_credential.rs
- vcx/libvcx/src/utils/libindy/wallet.rs
- vcx/libvcx/src/utils/mod.rs
Introduce macro "secret!" which hides PII information in release version.
If compiled in a debug mode, PII is still being logged.
> [VCX] Hide PII information from logs.

- libindy/src/services/pool/catchup.rs
**Issue:**
[IS-825](https://jira.hyperledger.org/browse/IS-825)
**Summary:**
Static analysis bug, `txns_cnt` were previously a `usize` and could not be negative, thus the comparison for less than 0 did not make sense.
An alternative solution would probably be to cast to `ìsize`, but this solution seems better and more understandable.
Signed-off-by: rasviitanen <rasviitanen@gmail.com>
> Fix bad comparison IS-825

- libindy/src/api/anoncreds.rs
- libindy/src/api/blob_storage.rs
- libindy/src/api/cache.rs
- libindy/src/api/crypto.rs
- libindy/src/api/did.rs
- libindy/src/api/ledger.rs
- libindy/src/api/logger.rs
- libindy/src/api/non_secrets.rs
- libindy/src/api/pairwise.rs
- libindy/src/api/payments.rs
- libindy/src/api/pool.rs
- libindy/src/api/wallet.rs
- libindy/src/services/payments.rs
- libindy/src/services/pool/state_proof/mod.rs
- libindy/src/utils/crypto/ed25519_box/sodium.rs
- libindy/src/utils/crypto/ed25519_sign/sodium.rs
- libindy/src/utils/crypto/pwhash_argon2i13/sodium.rs
- libindy/src/utils/crypto/randombytes/sodium.rs
- libindy/src/utils/logger.rs
- libindy/tests/utils/callback.rs
- libindy/tests/utils/mod.rs
- libindy/tests/utils/payments.rs
- libindy/tests/utils/wallet.rs
This PR removes some `extern crate` from the code because 
https://doc.rust-lang.org/reference/items/extern-crates.html
says this is unidiomatic since rust 2018.
```
Edition Differences: In the 2015 edition, crates in the extern prelude cannot be
referenced via use declarations, so it is generally standard practice to include 
extern crate declarations to bring them into scope.
Beginning in the 2018 edition, use declarations can reference crates in the 
extern prelude, so it is considered unidiomatic to use extern crate.
```
> extern crate is unidiomatic in Rust 2018

- cli/src/commands/ledger.rs
Previously some ledger commands always required opened pool even send
flag was set to false.
> [IS-1291] Correct behavior of offline ledger commands in CLI.

- Jenkinsfile.cd
- Jenkinsfile.ci
- wrappers/python/setup.py
`pytest` and `pytest-asyncio` aren't actually needed to use `python3-indy` as a library.
Hopefully I made the necessary adjustments to the CI/CD but I guess we'll see.
> Remove install dependency of pytest from python wrapper

- Jenkinsfile.cd
- Jenkinsfile.ci
- wrappers/python/setup.py
Install python wrapper test dependencies through pip extras.
Inspired by comments on PR #1683
> IS-1286: Python wrapper test dependencies through pip extras

- vcx/libvcx/scripts/provision_agent_keys.py
Instead of saying "see log" when said log doesn't exist, the provision script now says "Try again with '-v' for more details.
The payment_method is added to the provision script output with a default value of "null".  This should eventually be added to libvcx, and when that happens the value output by libvcx will not be overwritten.
> Fix incorrect reference to "log" on error. Also add payment_method to provision script output.

- libindy/src/commands/crypto.rs
Move the values that are part of the JWE protected header into constants to make it possible for the receiver of the encrypted message to (later) check those protected values whether they match the protocol.
> protected header field values

- libindy/src/services/crypto/mod.rs
- libindy/src/utils/crypto/chacha20poly1305_ietf/sodium.rs
This PR corrects information that the previous libindy code suggests about AAD.
1. AAD is NOT random. Randomness is in IV or nonce
2. AAD enables the sender of an encrypted message to tie extra data to the encryption. 
E.g. JWE [RFC 7516](https://tools.ietf.org/html/rfc7516) uses AAD to protect the 'JWE protected header'
AAD should be provided by the application/code using the encryption
libindy uses the verkey from the protected header
This PR removes the generation of random AAD values.
> correct facts about aad

- libindy/src/commands/payments.rs
- libindy/src/services/payments.rs
> use hex::encode instead of ursa::encode::bin2hex

- README.md
I found the URL of indy's wiki is broken. Maybe it means https://wiki.hyperledger.org/display/indy/ or https://wiki.hyperledger.org/display/indy/Hyperledger+Indy. and then I try to fix it
> update url of wiki

- libindy/src/services/crypto/mod.rs
The length of the base64 decoded bytes of the seed was not checked whether it is correct.
The PR adds the check
> check seed bytes length after base64 decoding

- experimental/plugins/postgres_storage/README.md
Fixes a broken link to the `github.com/ianco/indy-sdk` repository and makes a small correction to the instructions for checking out the plugin_storage_tests branch
Signed-off-by: John Bayne <baynejohn@gmail.com>
> Fix link to /ianco/indy-sdk postgres extension tests link

- docs/how-tos/how-to-add-a-new-API-call.md
- libindy/src/commands/anoncreds/issuer.rs
- libindy/src/commands/anoncreds/mod.rs
- libindy/src/commands/anoncreds/prover.rs
- libindy/src/commands/anoncreds/verifier.rs
- libindy/src/commands/blob_storage.rs
- libindy/src/commands/cache.rs
- libindy/src/commands/crypto.rs
- libindy/src/commands/did.rs
- libindy/src/commands/ledger.rs
- libindy/src/commands/mod.rs
- libindy/src/commands/non_secrets.rs
- libindy/src/commands/pairwise.rs
- libindy/src/commands/payments.rs
- libindy/src/commands/pool.rs
Production systems typically log at an INFO level. The number of
"command received" messages is high which creates a great deal of "noise" in the
logs. The "command received" log messages feel better suited for debugging and
thus have been moved to the DEBUG level.
Signed-off-by: Corin Kochenower <corin.kochenower@evernym.com>
> Change "command received" INFO messages to DEBUG

- vcx/dummy-cloud-agent/src/actors/agent_connection.rs
Agent connections were not properly registered in Router actor on restoration. Agent connections can now be still used after agency restart.
> Fix state restoration bug in dummy cloud agent

- vcx/dummy-cloud-agent/src/actors/agent.rs
- vcx/dummy-cloud-agent/src/actors/agent_connection.rs
Previously `debug` level basically didn't produce any logs whereas `trace` prints out too low level data (such as exact bytes in all vectors passed around).
Signed-off-by: Patrik Stas <patrik.stas@absa.co.za>
> Produce useful logs in debug level in dummy cloud agency

- vcx/dummy-cloud-agent/src/actors/agent.rs
- vcx/dummy-cloud-agent/src/actors/agent_connection.rs
- vcx/dummy-cloud-agent/src/utils/tests.rs
The presumption was that vcx is sending configuration option "logo_url", whereas vcx is actually sending "logoUrl" as you can see in the configuration builder here:
https://github.com/hyperledger/indy-sdk/blob/master/vcx/libvcx/src/messages/update_profile.rs#L59
> Fix bug where logo is never set for the agent

- ci/indy-pool.dockerfile
Building the docker image for running the test pool on localhost (https://github.com/hyperledger/indy-sdk#1-starting-the-test-pool-on-localhost) raised an error: python3-pyzmq version 18.x.x was available, but 17.0.0 needed. This PR makes the dependency on version 17.0.0 explicit.
Solves https://jira.hyperledger.org/browse/IS-1382.
> [IS-1382] Makes pyzmq version 17.0.0 dependency explicit

- wrappers/dotnet/indy-sdk-dotnet/indy-sdk-dotnet.csproj
Package name changed form 'Hyperledger.Indy.Sdk' to 'Hyperledger.Indy' due to conflicts with package updates. The package Hyperledger.Indy is owned by Hyperledger nuget account and we'll be able to do regular updates.
I was not able to establish contact with the owner of 'Hyperledger.Indy.Sdk' @srottem and transfer ownership.
> Update Nuget package name

- libindy/src/services/pool/state_proof/mod.rs
Removing clippy warning
Matching on `Some` with `ok()` is redundant
> warning: Matching on `Some` with `ok()` is redundant

- libindy/tests/utils/anoncreds.rs
This variable was unused to it was removed.
In general `pub static mut` are dangerous and an invitation to trouble in a multi-threaded environment like libindy.
> removed unused pub static mut variable

- Jenkinsfile.cd
- Jenkinsfile.ci
Should be reverted as soon as macos Jenkins worker would be fixed.
> Temporary disable pipelines for MacOS and iOS.

- libindy/ci/ubuntu18.dockerfile
> Revert "Remove devscirpts from Ubuntu 18.04 CI dockerimage to avoid 2 versions of libssl in the setup.".

- ci/indy-pool.dockerfile
Added 80 port to download key when using a proxy.
It allows to run samples smoother.
> added port 80 server alternative to dockerfile

- libindy/src/services/pool/pool.rs
> IS-1445: Invalid error message in the libindy logs in case of demoted nodes are on ledger

- vcx/dummy-cloud-agent/config/pgsql-config.json
- vcx/dummy-cloud-agent/config/sample-config.json
- vcx/dummy-cloud-agent/src/actors/agent.rs
- vcx/dummy-cloud-agent/src/actors/agent_connection.rs
- vcx/dummy-cloud-agent/src/actors/forward_agent.rs
- vcx/dummy-cloud-agent/src/actors/forward_agent_connection.rs
- vcx/dummy-cloud-agent/src/actors/router.rs
- vcx/dummy-cloud-agent/src/app.rs
- vcx/dummy-cloud-agent/src/app_admin.rs
- vcx/dummy-cloud-agent/src/domain/config.rs
- vcx/dummy-cloud-agent/src/main.rs
- vcx/dummy-cloud-agent/src/utils/tests.rs
`First commit:`
- A bit of backward improvement to previously submitted feature. 
If admin api is disabled, don't instantiate and use `admin` actor.
Also as I am submitting separate pull request adding `admin` actor 
unit tests, remove usage of `admin` from original unit tests to 
preserve original code flow where no `admin` is involved at all.
- Currently using hardcoded endpoint /agency instead of using 
prefix specified in config file. The bug was introduced by my 
earlier pull request https://github.com/hyperledger/indy-sdk/pull/1884
`Second commit`
- Removed config option app.enable_admin_api; instead added new
root configuration field "server_admin" which can be used to
enable/disable admin API and also to specify addresses where
admin api http server should be binded to.
- Admin …
> VCX Agency Admin api security/stability optimizations

- vcx/dummy-cloud-agent/src/actors/admin.rs
- vcx/dummy-cloud-agent/src/actors/agent_connection.rs
- vcx/dummy-cloud-agent/src/app.rs
- vcx/dummy-cloud-agent/src/app_admin.rs
- vcx/dummy-cloud-agent/src/indy/crypto.rs
- vcx/dummy-cloud-agent/src/indy/did.rs
- vcx/dummy-cloud-agent/src/indy/pairwise.rs
- vcx/dummy-cloud-agent/src/indy/wallet.rs
- vcx/dummy-cloud-agent/src/utils/futures.rs
- Added `dyn` when using trait objects - omitting `dyn` is deprecated
- Removed extra semicolons
> Fix rust warnings in vcx agency

- experimental/plugins/postgres_storage/README.md
- experimental/plugins/postgres_storage/src/errors/wallet.rs
- experimental/plugins/postgres_storage/src/lib.rs
- experimental/plugins/postgres_storage/src/postgres_storage.rs
- vcx/dummy-cloud-agent/config/pgsql-config.json
- Strategy `MultiWalletSingleTable` is creating many connection pools, one connection pool per wallet
- This adds `MultiWalletSingleTableSharedPool` strategy which shares postgre connections across wallets
- This also happens to remove several `unsafe` sections in the plugin
> Add pgsql storage strategy sharing connection pool between wallets

- experimental/plugins/postgres_storage/src/lib.rs
- experimental/plugins/postgres_storage/src/postgres_storage.rs
MultiWalletSingleTable Postgres wallet has default DB name 'Wallets'. This allows the name to be configured during wallet creation, open and delete as well as when init'ing the storage type.
Another attempt to fix [Jira 1443](https://jira.hyperledger.org/browse/IS-1443)
This PR replaces PR #1979 and PR #2028
This PR contains all of the fixes suggested by @ianco and @Artemkaaas 
Signed-off-by: Aaron Reed <aaronr@us.ibm.com>
> add support for specifying database name for postgres wallet.  Jira 1443

- experimental/plugins/postgres_storage/src/lib.rs
- experimental/plugins/postgres_storage/src/postgres_storage.rs
Tests in pgsql are still failing randomly when running
```
RUST_BACKTRACE=full WALLET_SCHEME=MultiWalletSingleTable cargo test  -- --nocapture --test-threads=1
```
this PR fixes the issues. This PR is addition to previously merged https://github.com/hyperledger/indy-sdk/pull/2033/files
In addition fixed some warnings
> Fix intermittent pgsql wallet unittest issues

- vcx/wrappers/node/src/api/connection.ts
`sendMessage` in NodeJS wrapper is calling rust here:
https://github.com/hyperledger/indy-sdk/blob/master/vcx/libvcx/src/api/connection.rs#L801
which propagates result of `send_generic_message `
defined here
https://github.com/hyperledger/indy-sdk/blob/master/vcx/libvcx/src/connection.rs#L842
so: 
1. For legacy this calls
https://github.com/hyperledger/indy-sdk/blob/master/vcx/libvcx/src/connection.rs#L398
returning UID according to what was returned from agency.
2. But for Aries is called
https://github.com/hyperledger/indy-sdk/blob/master/vcx/libvcx/src/v3/handlers/connection/connection.rs#L186
which always returns empty String. 
In NodeJS wrapper there was validation making sure that the string passed to callback is not empty. Hence this would always fail when using Aries with error …
> Dont fail with Error:success when sending Aries message from Nodejs LibVCX

- vcx/dummy-cloud-agent/src/utils/wallet.rs
Generated verkey is usually 44 characters long, but occasionally happens to be 43 chars long. That is causing false positive failure in dummy cloud agent unit test.
> Fix interminnent failure in dummy cloud agent unit test

- vcx/wrappers/node/demo/faber.js
- vcx/wrappers/python3/demo/faber.py
- vcx/wrappers/python3/vcx/api/utils.py
I tried to use vcx with the sovrin builder network and got an error while starting `faber.py` at step 3. Before fixes, it always returns.
```bash
#1 Provision an agent and wallet, get back configuration details
#2 Initialize libvcx with new configuration
#2.1 Accept transaction author agreement
#3 Create a new schema on the ledger
Traceback (most recent call last):
File "faber.py", line 194, in <module>
loop.run_until_complete(main())
File "/home/user/.pyenv/versions/3.7.6/lib/python3.7/asyncio/base_events.py", line 583, in run_until_complete
return future.result()
File "faber.py", line 73, in main
schema = await Schema.create(f'schema{str(random.randint(1, 101))}', 'degree schema asd', version, ['email', 'first_name', 'last_name'], 0)
File …
```
> Fix taa py wrapper

- vcx/wrappers/ios/vcx/ConnectMeVcx.h
- vcx/wrappers/ios/vcx/ConnectMeVcx.m
- vcx/wrappers/ios/vcx/include/libvcx.h
Added APIs
* connectionGetState, connectionUpdateState, connectionRelease
* credentialRelease
* proofGetRequests, proofGetState, proofUpdateState, proofRelease
Fixed 
* Fixed the parameter name of vcx_disclosed_proof_get_requests method (offers --> requests)
There are several data types for handles (connectionHandle, credentialHandle, proofHandle), and they are used Interchangeably. For example, for the connectionHandle, three data types (VcxHandle, NSInteger, vcx_connection_handle_t) are used in the code... I believe that there should be a consistent way of implementing it. In this PR, I only use NSInteger for all handles.
> VCX iOS wrapper updates

- libindy/Cargo.toml
Fix build error. Use latest version of "quote" crate since "quote=1.0.2" is yanked and use latest version of "failure" crate to avoid compile error.
> Fix build error. Use latest version of "quote" (yanked), "failure" crates

- libindy/mac.build.sh
Update build script for Mac to use correct open ssl path. By default, MacOS comes with preinstalled open ssl at the location `/usr/local/Cellar`, but the brew package previously in this script installs updated open ssl at different location. This causes libindy not to load correctly.
> Use correct path for OpenSSL in local Mac build script

- vcx/libvcx/src/api/connection.rs
- vcx/libvcx/src/v3/handlers/connection/connection.rs
- vcx/libvcx/src/v3/messages/a2a/mod.rs
Fixed sending generic msgs as BasicMsg (these are still sent if content is plain text).
> VCX Aries: Fixed double escaping and sending of generic msgs.

- Jenkinsfile.cd
- Jenkinsfile.ci
- libindy/ci/centos.dockerfile
- libindy/ci/ubuntu.dockerfile
- libindy/ci/ubuntu18.dockerfile
- vcx/ci/ubuntu.dockerfile
- vcx/libvcx/build_scripts/ios/mac/mac.01.libindy.setup.sh
Due to unidentified reason, builds started fail with
```
Compiling quote v0.6.13
Compiling aho-corasick v0.7.12
error[E0658]: `cfg(doctest)` is experimental and subject to change
--> /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.12/src/lib.rs:190:7
|
190 | #[cfg(doctest)]
|       ^^^^^^^
|
= note: for more information, see https://github.com/rust-lang/rust/issues/62210
error[E0658]: `cfg(doctest)` is experimental and subject to change
--> /home/indy/.cargo/registry/src/github.com-1ecc6299db9ec823/aho-corasick-0.7.12/src/lib.rs:194:7
|
194 | #[cfg(doctest)]
|       ^^^^^^^
|
= note: for more information, see https://github.com/rust-lang/rust/issues/62210
```
As is noted https://stackoverflow.com/questions/62383641/errore0658-cfgdoctest-is-experimental-and-subje …
> Update rust toolchain from 1.39 to 1.40

- wrappers/python/indy/ledger.py
The default value for these parameters was defined as a c_int rather than a c_int64, which may have a different size depending on the platform.
> Fix c_int usage in python wrapper

- vcx/libvcx/src/messages/get_message.rs
- vcx/libvcx/src/v3/messages/a2a/mod.rs
Strict aries protocol (V4) uses cross domain message format. Hence, both received and returned messages should be in aries format, and so when calling `vcx_messages_download`,  the user may expect to obtain messages in aries format, i.e. their serialized version (i.e. including the `@type` field).
This PR fixes the inconsistent behavior introduced with version V4, where some A2A messages (e.g. `PresentationRequest`, `CredentialOffer`, `Presentation`, etc.) were deserialized (i.e. `@type` field was read and stripped), whereas others were returned as received from the agency (i.e. with `@type` field).
> Fix message decrypting for V4

- vcx/libvcx/src/v3/messages/issuance/credential.rs
- vcx/libvcx/src/v3/messages/issuance/credential_offer.rs
- vcx/libvcx/src/v3/messages/issuance/credential_proposal.rs
According to aries rfcs 
https://github.com/hyperledger/aries-rfcs/tree/master/features/0036-issue-credential
https://github.com/hyperledger/aries-rfcs/tree/master/features/0453-issue-credential-v2
the comment field is an optional field. 
However, libvcx expects this as a mandatary, so if the comment is empty it causes Json parsing error 
```
Caused by: Cannot deserialize A2A message: missing field 'comment'
```
This PR fixes this issue.
> VCX - Make a comment field as an optional

- experimental/plugins/postgres_storage/src/postgres_storage.rs
Updates ix_tags_encrypted_value to use md5 so it can support larger values (eg images)
FYI @ianco 
Signed-off-by: Jacob Saur <jsaur@kiva.org>
> Update postgres index to use md5

- wrappers/nodejs/README.md
- wrappers/nodejs/src/index.js
- wrappers/nodejs/src/indy.cc
Libindy's build_get_attrib_request API expects the arguments in a different order
Refer to: https://github.com/hyperledger/indy-sdk/blob/d8c68d7894be07ef50f5d1c4aa6326a201da030f/libindy/src/api/ledger.rs#L564
> nodejs: fix order of arguments to buildGetAttribRequest

- wrappers/java/src/main/java/org/hyperledger/indy/sdk/anoncreds/Anoncreds.java
Fixing issue where `indy_prover_delete_credential` in Java was expecting to get back string in callback method does not return one. 
This was causing crashes on Android 23 devices and below
```
/apex/com.android.runtime/lib64/bionic/libc.so (strlen+16) (BuildId: 99d256d401014e290f38edaacced78da)
/data/app/net.globalid.aries.test-WNnANtndag0UbHLXUDTDjg==/lib/arm64/libjnidispatch.so (Java_com_sun_jna_Native_getStringBytes+32)
/apex/com.android.runtime/lib64/libart.so (art_quick_generic_jni_trampoline+144) (BuildId: 696d39ffaba44c5a3159a32a6f139534)
/memfd:/jit-cache (deleted) (com.sun.jna.Native.getString+76)
...
```
> Fix indy_prover_delete_credential JNA callback

- wrappers/java/src/test/java/org/hyperledger/indy/sdk/interaction/AnoncredsVerifyProofAfterCredentialRevokeTest.java
The declared field was never initialized. From that, the path was always `null/revoc_dir/` which works for most environments as it will just create a folder with name null. But one some environment this becomes an issue. For example, Android would take the current directory in `/` and would then try to create directory `/null`. Application space of course does not have permission to write to `/` so this would fail with IO Error.
> Java wrapper: Setting revoc dir in tests

- wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibIndy.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/pool/Pool.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/pool/ListPoolsTest.java
A wrapper function for the `indy_list_pools` Indy SDK function was missing in the Java SDK.
> Fixes #2304 Java wrapper for `indy_list_pools` Indy SDK function

- experimental/plugins/postgres_storage/src/postgres_storage.rs
https://github.com/hyperledger/indy-sdk/pull/2232 supported saving big files in postgres.
However, it did not apply to `MultiWalletSingleTable` and `MultiWalletSingleTableSharedPool` modes.
This PR solves the above issue.
@ianco 
Signed-off-by: Ethan Sung <baegjae@gmail.com>
> Update postgres index in multi-wallet to use md5

- libindy/Cargo.lock
- libindy/indy-api-types/Cargo.toml
- libindy/indy-api-types/src/errors.rs
- libindy/indy-wallet/Cargo.toml
- libindy/indy-wallet/src/storage/default/mod.rs
- libindy/indy-wallet/src/storage/default/transaction.rs
The current version of `rusqlite` (0.20.0) is transitively dependent on `linked-hash-map v0.5.3`, which contains a bug ([fixed](https://github.com/contain-rs/linked-hash-map/pull/106) in version `0.5.4`). This bug causes runtime panics due to uninitialized reference on wallet access since rust `1.48.0`. See [here](https://github.com/mehcode/config-rs/issues/158), [here](https://github.com/hyperledger/aries-vcx/pull/126), and [here](https://github.com/hyperledger/indy-sdk/pull/2311).
This PR updates version of rusqlite which fixes the bug (replicating the changes in #2311 with green DCO), as the latest version of rusqlite removes dependency on `linked-hash-map`.
Signed-off-by: Miroslav Kovar <miroslavkovar@protonmail.com>
> Update Rusqlite to version 0.25.3

- libindy/src/api/pool.rs
- libindy/src/domain/pool.rs
- libindy/src/services/pool/networker.rs
- libindy/src/services/pool/pool.rs
- libindy/src/services/pool/request_handler.rs
implementation for issue [#2399](https://github.com/hyperledger/indy-sdk/issues/2399)
Signed-off-by: Vitalij Reicherdt <vitalij.reicherdt@commerzbank.com>
> support setting ZMQ socks proxy

- Jenkinsfile.cd
- Remove the blocking input before the Cargo publish step.
- This is causing too many build resources issues to leave in place.
- Removing without adding the check and retry logic to see if and how much of an issue this still is.
- Related issue references:
- https://github.com/hyperledger/indy-sdk/issues/2309
- https://github.com/hyperledger/indy-sdk/issues/2395
Signed-off-by: Wade Barnes <wade@neoterictech.ca>
> Remove the blocking input in the CD pipeline.

- libindy/ci/wrappers/python.dockerfile
The pipeline is failing in the build-image-python step.
Pip is complaining about the wrong url. 
```
#6 [3/4] RUN curl -fsSL -o- https://bootstrap.pypa.io/pip/get-pip.py | python3.6
#6 sha256:ec08f7fc3ed30f11c7a36d067994d6e26242634d813008d8a05d9731c2997e56
#6 0.432 ERROR: This script does not work on Python 3.6 The minimum supported Python version is 3.7. Please use https://bootstrap.pypa.io/pip/3.6/get-pip.py instead.
#6 ERROR: executor failed running [/bin/sh -c curl -fsSL -o- https://bootstrap.pypa.io/pip/get-pip.py | python3.6]: exit code: 1
```
This PR should fix that.
> Fixes pip bootstrap error

- experimental/plugins/postgres_storage/Cargo.toml
- experimental/plugins/postgres_storage/src/postgres_storage.rs
Add basic TLS support for postgres plugin. Can specify tls_ca to allow specifying a ca file.
Signed-off-by: Kim Ebert <kim@indicio.tech>
> feat: add basic ssl for postgres
