hyperledger/indy-sdk

- src/errors/anoncreds.rs
- src/errors/crypto.rs
- src/errors/mod.rs
- src/errors/sovrin.rs
- src/errors/wallet.rs
- src/lib.rs
* Implemented basic error types for each component
* Provided basic tests for error types
* It is hard to determine exact list of error cases on this stage, so they will be enhanced during services implementation
> * Implemented basic error types for each component

- src/api/sovrin.rs
- src/commands/mod.rs
- src/commands/sovrin.rs
- src/constants.rs
- src/lib.rs
- src/services/sovrin.rs
* Added constants
* Added commands for  Sovring API (in progress)
> * Added constants

- src/services/pool/mod.rs
- src/services/pool/types.rs
Implement comparison for Replies in pool service - now wait f+1 *same* replies instead of *any* replies.
> Hotfix/ PoolLedger check Replies content and wait f+1 same

- wrappers/java/README.md
- wrappers/java/lib/.gitignore
- wrappers/java/pom.xml
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ErrorCode.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibSovrin.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/SovrinConstants.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/SovrinException.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/SovrinJava.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/anoncreds/Anoncreds.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/anoncreds/AnoncredsJSONParameters.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/anoncreds/AnoncredsResults.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ledger/Ledger.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ledger/LedgerJSONParameters.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ledger/LedgerResults.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/pool/Pool.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/pool/PoolJSONParameters.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/pool/PoolResults.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/signus/Signus.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/signus/SignusJSONParameters.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/signus/SignusResults.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/wallet/Wallet.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/wallet/WalletJSONParameters.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/wallet/WalletResults.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/LedgerTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/PoolTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/SignusTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/WalletTest.java
Per discussion at https://jira.hyperledger.org/browse/INDY-184, I propose to hereby contribute this project https://github.com/projectdanube/indy-sdk-java to the **wrapper/** folder of **indy-sdk**.
It's not thoroughly tested, and a wrapper for the **agent.rs** module is still missing at this point.
But I am already successfully using this for some PoC work and am planning to continue improving it.
> add Java wrapper

- include/sovrin_agent.h
- src/api/agent.rs
- src/commands/agent.rs
- src/services/agent.rs
- tests/agent.rs
- tests/utils/agent.rs
- tests/utils/callback.rs
* client verification
* implement rm_identity
> Agent2agent connection client verification

- ci/sovrin-pool.dockerfile
This approach provide clear way to update pool to the latest version on CI.
> Introduce fixed version of sovrin node for Jenkins pipeline.

- tests/anoncreds.rs
- tests/demo.rs
- tests/ledger.rs
- tests/signus.rs
Added new tests
issuer_create_and_store_claim_def_works_for_invalid_did
issuer_create_and_store_claim_def_works_for_correct_signature_type
prover_create_master_secret_works_for_empty_name
prover_get_claims_for_proof_req_works_for_revealed_attr_for_specific_issuer
prover_get_claims_for_proof_req_works_for_revealed_attr_with_other_issuer
prover_get_claims_for_proof_req_works_for_satisfy_predicate_by_specific_issuer_and_schema
indy_claim_def_request_works_without_signature
indy_create_my_did_works_for_exists_crypto_type
indy_replace_keys_works_for_seed
indy_store_their_did_works_without_did
indy_store_their_did_works_for_correct_crypto_type
indy_verify_works_for_other_signer
indy_replace_keys_works_for_not_invalid_crypto_type
Corrected
prover_store_claim_works
> Added new integration tests

- wrappers/java/src/main/java/org/hyperledger/indy/sdk/agent/Agent.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/wallet/Wallet.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/wallet/WalletTypeInmem.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/agent/AgentConnectTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/anoncreds/IssuerCreateAndStoreClaimDefinitionTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/anoncreds/ProverCreateMasterSecretTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/anoncreds/ProverCreateProofTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/anoncreds/ProverGetClaimsForProofRequestTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/anoncreds/ProverStoreClaimTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/anoncreds/VerifierVerifyProofTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/demo/AgentDemoTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/demo/LedgerDemoTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/AttribRequestsTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/ClaimDefRequestsTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/GetTxnRequestTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/NodeRequestsTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/NymRequestsTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/RequestsTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/SchemaRequestsTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/signus/CreateMyDidTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/signus/ReplaceKeysTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/signus/SignTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/signus/StoreTheirDidTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/signus/VerifyTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/wallet/CloseWalletTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/wallet/CreateWalletTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/wallet/DeleteWalletTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/wallet/OpenWalletTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/wallet/RegisterWalletTypeTest.java
Refactored tests in Java wrapper
> Implemented register wallet tests for Java wrapper. 

- libindy/include/indy_ledger.h
* replaces the duplicated doc comment
> indy_build_get_txn_request doc comment

- Jenkinsfile
- samples/python/src/main.py
Change indy-node for pool in CI testing to latest stable (1.1.33)
> RC3 for v1.0.0

- Jenkinsfile.cd
> Fix windows tests

- wrappers/dotnet/indy-sdk-dotnet-test/LedgerTests/NodeRequestTest.cs
- wrappers/dotnet/indy-sdk-dotnet-test/LedgerTests/NymRequestTest.cs
- wrappers/dotnet/indy-sdk-dotnet-test/LedgerTests/RequestTest.cs
- wrappers/dotnet/indy-sdk-dotnet-test/LedgerTests/SchemaRequestTest.cs
Fixes issues highlighted in IS- 363.
> Fix State Proof support related regressions in tests.

- libindy/include/indy_pairwise.h
- libindy/src/api/mod.rs
- libindy/src/api/pairwise.rs
- libindy/src/commands/mod.rs
- libindy/src/commands/pairwise.rs
- libindy/src/services/signus/types.rs
- libindy/tests/pairwise.rs
- libindy/tests/utils/callback.rs
- libindy/tests/utils/mod.rs
- libindy/tests/utils/pairwise.rs
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibIndy.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/pairwise/Pairwise.java
- wrappers/java/src/test/java/org/hyperladger/indy/sdk/pairwise/CreatePairwiseTest.java
- wrappers/java/src/test/java/org/hyperladger/indy/sdk/pairwise/GetPairwiseTest.java
- wrappers/java/src/test/java/org/hyperladger/indy/sdk/pairwise/ListPairwiseTest.java
- wrappers/java/src/test/java/org/hyperladger/indy/sdk/pairwise/PairwiseExistsTest.java
- wrappers/java/src/test/java/org/hyperladger/indy/sdk/pairwise/SetPairwiseMetadataTest.java
- wrappers/python/indy/pairwise.py
- wrappers/python/tests/conftest.py
- wrappers/python/tests/pairwise/test_create_pairwise.py
- wrappers/python/tests/pairwise/test_get_pairwise.py
- wrappers/python/tests/pairwise/test_list_pairwise.py
- wrappers/python/tests/pairwise/test_pairwise_exists.py
- wrappers/python/tests/pairwise/test_set_pairwise_metadata.py
> Added new Api calls for better pirwise support

- libindy/src/services/pool/mod.rs
- libindy/tests/pool.rs
- libindy/tests/utils/pool.rs
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/pool/CreatePoolTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/utils/PoolUtils.java
> Added handling of empty genesis txn file.

- libindy/src/commands/anoncreds/prover.rs
> Get claims function must return unblinded attributes

- libindy/tests/crypto.rs
- libindy/tests/utils/callback.rs
- libindy/tests/utils/crypto.rs
* Added tests for crypto_sign/crypto_verify
> Tests for crypto_sign/crypto_verify

- ci/indy-pool.dockerfile
Signed-off-by: Corin Kochenower <corin.kochenower@evernym.com>
> Must use valid, tested version for indy-* deps

- libindy/include/indy_signus.h
- libindy/src/api/signus.rs
- libindy/src/commands/signus.rs
- libindy/tests/signus.rs
- libindy/tests/utils/callback.rs
- libindy/tests/utils/signus.rs
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibIndy.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/signus/Signus.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/signus/KeyForLocalDidTest.java
- wrappers/python/indy/signus.py
- wrappers/python/tests/signus/test_key_for_local_did.py
* Implemented new key_for_local_did call
* Added tests for key_for_local_did
* Added python and java wrappers for key_for_local_did and corresponded tests
> Ledgerless DIDs support

- Specs/libindy-objc/1.1.1/libindy-objc.podspec.json
- libindy/Cargo.lock
- libindy/Cargo.toml
- libindy/debian/changelog
- wrappers/ios/libindy-pod/Podfile
- wrappers/java/pom.xml
- wrappers/python/setup.py
* add new version of libindy-objc
> 1.1.1 RC 1

- cli/src/commands/mod.rs
- cli/src/commands/wallet.rs
- cli/src/main.rs
Signed-off-by: Vyacheslav Gudkov <vyacheslav.gudkov@dsr-company.com>
> Boilerplate added

- cli/src/command_executor.rs
- cli/src/commands/did.rs
- cli/src/commands/ledger.rs
- cli/src/commands/mod.rs
- cli/src/commands/wallet.rs
- cli/src/indy_context.rs
- cli/src/libindy/pool.rs
- cli/src/main.rs
- cli/src/utils/mod.rs
- cli/src/utils/term.rs
- libindy/src/services/ledger/mod.rs
- libindy/src/services/ledger/types.rs
- libindy/tests/ledger.rs
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/NodeRequestsTest.java
- wrappers/python/tests/ledger/test_build_node_request.py
> Cli commands core refactoring

- wrappers/python/indy/libindy.py
Signed-off-by: Dmitry Surnin <dmitry.surnin@dsr-company.com>
> Change log level to debug

- doc/mac-build.md
Signed-off-by: mountbranch <jonatan@c8.works>
> update libsodium install to install version 1.0.12

- Specs/libindy/1.1.0-1/libindy.podspec.json
> Updated source field in libindy Ios wrapper podspec json

- cli/cli.dockerfile
Signed-off-by: Sergey Minaev <sergey.minaev@dsr-company.com>
> [cli] Add simple dockerfile for CLI.

- Jenkinsfile.cd
Signed-off-by: Andrey Kononykhin <andkononykhin@gmail.com>
> Set limit to 28 days to keep old builds and artifacts

- cli/src/commands/ledger.rs
> Corrected Get Nym output in Indy Cli

- libindy/src/services/pool/mod.rs
- libindy/tests/pool.rs
- libindy/tests/utils/pool.rs
> Added handling of empty lines in pool_genesis_txn file

- cli/src/commands/ledger.rs
> Added seq_no to get-schema Cli output

- Jenkinsfile.cd
- Jenkinsfile.ci
> Clean docker before and after work with pool.

- Jenkinsfile.ci
> Changed device in ios pipeline

- cli/src/commands/did.rs
- doc/cli-design.md
> Deleted cid param from Did::new Cli command

- cli/src/commands/wallet.rs
- cli/src/libindy/callbacks.rs
- cli/src/libindy/did.rs
- cli/src/libindy/ledger.rs
- cli/src/libindy/pool.rs
- cli/src/libindy/wallet.rs
> Deleted freshness_time param from wallet commands

- cli/src/commands/wallet.rs
> Corrected prompt for Indy-Cli

- doc/cli-design.md
> Updated cli documentation

- cli/src/commands/wallet.rs
> Corrected prompt behavior

- cli/src/commands/ledger.rs
- cli/src/commands/pool.rs
> Ledger pool-upgrade improvements

- cli/src/commands/ledger.rs
> Filter data fields in transaction response

- cli/build.rs
> Modified cli/build.rs file

- cli/src/commands/ledger.rs
> Improved regular expression for extracting of errors

- wrappers/python/indy/anoncreds.py
> Corrected condition for get_claims_for_proof_req callback creation

- Jenkinsfile.cd
- Jenkinsfile.ci
> Fixed docker cleaning function

- Jenkinsfile.ci
- libindy/src/api/did.rs
- libindy/src/commands/did.rs
- libindy/src/services/ledger/types.rs
- libindy/tests/did.rs
- libindy/tests/utils/callback.rs
- libindy/tests/utils/did.rs
- wrappers/python/indy/did.py
> Corrected GetAttribData object. Set verkey field as Optional

- cli/src/commands/ledger.rs
> Deleted unnecessary apostrophe at the end of the line "target"

- libindy/tests/did.rs
> Added timeout before getting of key for did

- cli/src/commands/wallet.rs
> Corrected help for main params

- libindy/src/commands/anoncreds/verifier.rs
- libindy/tests/anoncreds.rs
- samples/java/src/main/java/Anoncreds.java
- wrappers/dotnet/indy-sdk-dotnet-test/DemoTests/AnonCredsDemoTest.cs
- wrappers/ios/libindy-pod/Indy-demoTests/Case Tests/Anoncreds/AnoncredsMediumCasesDemos.m
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/demo/AnoncredsDemoTest.java
> Corrected verifier attributes checking

- cli/src/commands/did.rs
- cli/src/commands/ledger.rs
- cli/src/commands/pool.rs
- cli/src/commands/wallet.rs
- cli/src/utils/table.rs
Corrected verifier attributes checking
> Rotate-key available on read-only pool

- doc/cli-design.md
Changing sample seed to 32 characters so it's directly usable. Removing publish_to_ledger parameter which was not implemented.
> Design Doc Tweaks

- cli/src/command_executor.rs
> Changed Completer implementation

- libindy/tests/did.rs
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/did/GetEndpointForDidTest.java
- wrappers/python/tests/did/test_get_endpoint_for_did.py
> Sleep 1 second in get_endpoint_for_did tests

- Specs/libindy-objc/1.3.1/libindy-objc.podspec.json
- Specs/libindy/1.3.1/libindy.podspec.json
- libindy/Cargo.lock
- libindy/Cargo.toml
- libindy/build-libindy-ios.sh
- libindy/debian/changelog
- wrappers/ios/libindy-pod/Podfile
- wrappers/java/pom.xml
- wrappers/python/setup.py
> Version incremented to 1.3.1

- libindy/src/services/pool/mod.rs
> Chenged flag for ZMQ sending messages

- doc/getting-started/getting-started.md
These changes clean up the new Getting Started Guide to add clarity
to grammar and spelling and some verbiage flows.
Signed-off-by: TechWritingWhiz <techwritingwhiz@gmail.com>
> Clean up of New Getting Started Guide

- ci/indy-pool.dockerfile
- doc/getting-started/getting-started.md
- samples/python/setup.py
> Fixed typo

- libindy/src/api/anoncreds.rs
- libindy/src/api/blob_storage.rs
- libindy/src/commands/anoncreds/issuer.rs
- libindy/src/commands/anoncreds/prover.rs
- libindy/src/commands/anoncreds/tails.rs
- libindy/src/commands/blob_storage.rs
- libindy/src/services/anoncreds/issuer.rs
- libindy/src/services/anoncreds/prover.rs
- libindy/src/services/anoncreds/types.rs
- libindy/src/services/anoncreds/verifier.rs
- libindy/src/services/blob_storage/default_writer.rs
- libindy/src/services/wallet/mod.rs
- libindy/tests/anoncreds.rs
- libindy/tests/demo.rs
- libindy/tests/utils/anoncreds.rs
- libindy/tests/utils/blob_storage.rs
- libindy/tests/utils/callback.rs
- libindy/tests/utils/mod.rs
> Recovered Libindy integration tests

- Specs/libindy/1.3.1-1/libindy.podspec.json
> Added pod spec file for Blob_storage

- libindy/debian/control
> Set libzmq3-dev as required dependency for Libindy debian package

- libindy/src/commands/blob_storage.rs
- libindy/tests/crypto.rs
- libindy/tests/demo.rs
- libindy/tests/did.rs
- libindy/tests/ledger.rs
- libindy/tests/pairwise.rs
- libindy/tests/pool.rs
- libindy/tests/utils/anoncreds.rs
- libindy/tests/wallet.rs
Signed-off-by: Sergey Minaev <sergey.minaev@dsr-company.com>
> Fix compilation errors and some warnings.

- Jenkinsfile.cd
- Jenkinsfile.ci
- samples/python/setup.py
- wrappers/python/setup.py
Signed-off-by: Andrey Kononykhin <andkononykhin@gmail.com>
> [WIP] Pipelines for authz branches

- libindy/build-libindy-ios.sh
> Corrected build-ios script

- libindy/src/commands/anoncreds/issuer.rs
- libindy/src/services/anoncreds/prover.rs
- libindy/tests/anoncreds.rs
- libindy/tests/utils/anoncreds.rs
> Added one integration test for revocation

- doc/how-tos/README.md
- doc/how-tos/issue-credential/README.md
- doc/how-tos/negotiate-proof/README.md
- doc/how-tos/rotate-key/README.md
- doc/how-tos/save-schema-and-cred-def/README.md
- doc/how-tos/send-secure-msg/README.md
- doc/how-tos/write-did-and-query-verykey/README.md
> Add READMEs to browse how-tos

- README.md
- doc/how-tos/save-schema-and-cred-def/java/README.md
> Add links to Rocket.Chat

- doc/how-tos/issue-credential/java/IssueCredential.java
- doc/how-tos/issue-credential/python/issue_credential.py
- doc/how-tos/proof-negotiation/java/ProofNegotiation.java
- doc/how-tos/proof-negotiation/python/proof_negotiation.py
- doc/how-tos/rotate-key-on-the-ledger/java/RotateKeyOnTheLedger.java
- doc/how-tos/rotate-key-on-the-ledger/python/rotate_key_on_the_ledger.py
- doc/how-tos/send-secure-msg/java/SendSecureMessage.java
- doc/how-tos/write-did-and-query-verykey/java/WriteDIDAndQueryVerkey.java
- doc/how-tos/write-did-and-query-verykey/python/write_did_and_query_verkey.py
- doc/how-tos/write-schema-and-credential-definition/java/WriteSchemaAndCredDef.java
- doc/how-tos/write-schema-and-credential-definition/python/write_schema_and_cred_def.py
Signed-off-by: Janko Krstic <keichiri@protonmail.com>
> Python and Java code for how-tos

- doc/how-tos/README.md
- doc/how-tos/issue-credential/README.md
- doc/how-tos/issue-credential/java/README.md
- doc/how-tos/negotiate-proof/README.md
- doc/how-tos/negotiate-proof/python/README.md
- doc/how-tos/rotate-key/java/README.md
- doc/how-tos/save-schema-and-cred-def/README.md
- doc/how-tos/save-schema-and-cred-def/java/README.md
- doc/how-tos/write-did-and-query-verkey/java/README.md
- doc/how-tos/write-did-and-query-verkey/python/README.md
Includes edits for all the how-to documents submitted so far.
Signed-off-by: mistybledsoe <misty.bledsoe@evernym.com>
> Edits for the How-To documents

- wrappers/python/indy/anoncreds.py
- wrappers/python/indy/did.py
- wrappers/python/indy/ledger.py
> Corrected None cheking in Python wrapper

- libindy/src/services/pool/transaction_handler.rs
> Request time was decreased from 2000 to 100 seconds

- libindy/src/commands/anoncreds/issuer.rs
- libindy/src/commands/anoncreds/tails.rs
- libindy/src/services/blob_storage/default_reader.rs
- libindy/src/services/blob_storage/default_writer.rs
- libindy/tests/anoncreds.rs
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/interaction/AnoncredsRevocationInteractionTest.java
> Fixed interaction tests in Java wrapper

- wrappers/python/tests/ledger/test_submit_request.py
> FIxed get txn test in Python wrapper

- libindy/src/services/pool/catchup.rs
Signed-off-by: Sergey Minaev <sergey.minaev@dsr-company.com>
> Revert catchup round timeout.

- ci/indy-pool.dockerfile
- doc/getting-started/getting-started.dockerfile
- doc/getting-started/getting-started.ipynb
- samples/java/pom.xml
- samples/python/setup.py
- samples/python/src/anoncreds_revocation.py
- samples/python/src/main.py
> Updated Libindy version in samples

- libindy/src/services/wallet/mod.rs
- libindy/tests/pairwise.rs
> Fixed compilation error

- cli/README.md
Include note about comments in batch mode (#673).
Signed-off-by: Daniel Bluhm <bluhmdan@gmail.com>
> Update cli README

- libindy/src/api/payments.rs
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibIndy.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/payments/Payments.java
> Rename indy_list_address method

- libindy/Cargo.lock
- libindy/Cargo.toml
- libindy/src/api/mod.rs
- libindy/src/errors/wallet.rs
- libindy/src/lib.rs
- libindy/src/services/wallet/encryption.rs
- libindy/src/services/wallet/iterator.rs
- libindy/src/services/wallet/language.rs
- libindy/src/services/wallet/mod.rs
- libindy/src/services/wallet/query_encryption.rs
- libindy/src/services/wallet/storage/default/mod.rs
- libindy/src/services/wallet/storage/default/query.rs
- libindy/src/services/wallet/storage/mod.rs
- libindy/src/services/wallet/storage/plugged.rs
- libindy/src/services/wallet/wallet.rs
This is all the work so far.
Plugged wallet is being finished by Darko.
Enterprise wallet is being finished by Darko and Nem.
We expect that to be added in next couple of days.
After that, the commented tests will be uncommented
> Default wallet storage implementation with encryption layer and wql

- CHANGELOG.md
Clarified the impact of the changes and implications for the next release.
Signed-off-by: richard-oss@esplins.org
> Added more detail to the change log.

- ci/acceptance/ubuntu_acceptance.dockerfile
- samples/java/pom.xml
- samples/python/setup.py
> Updated dockerfile for acceptance testing

- libindy/libnullpay/src/lib.rs
- libindy/libnullpay/src/libindy/ledger.rs
- libindy/libnullpay/src/libindy/payments.rs
- libindy/libnullpay/src/payment_method.rs
- libindy/libnullpay/src/utils/callbacks.rs
- libindy/libnullpay/src/utils/rand.rs
- libindy/libnullpay/src/utils/sequence.rs
> Refactor macros and structs

- libindy/src/services/wallet/mod.rs
> Fixed wallet tests compilation errors

- wrappers/java/src/test/java/org/hyperledger/indy/sdk/IndyIntegrationTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/anoncreds/AnoncredsIntegrationTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/wallet/CreateWalletTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/wallet/OpenWalletTest.java
> Java tests wallet credentials

- libindy/src/commands/payments.rs
- libindy/tests/payments.rs
- libindy/tests/utils/payment_method.rs
> Fix errors

- cli/src/commands/ledger.rs
- cli/src/commands/mod.rs
- cli/src/commands/payment_address.rs
> Added set of tests for Cli payment commands

- cli/src/commands/ledger.rs
- cli/src/libindy/ledger.rs
- cli/src/libindy/payment.rs
- libindy/include/indy_ledger.h
- libindy/src/api/ledger.rs
- libindy/src/api/payments.rs
- libindy/src/commands/ledger.rs
- libindy/tests/ledger.rs
- libindy/tests/utils/constants.rs
- libindy/tests/utils/ledger.rs
> Multi Signature

- Specs/libindy/1.4.0-1/libindy.podspec.json
> Added new iOS podspec

- cli/Cargo.toml
- cli/src/commands/common.rs
- cli/src/commands/ledger.rs
- cli/src/commands/payment_address.rs
- libindy/tests/payments.rs
- libindy/tests/utils/payments.rs
> Fix code style. Add feature to payment tests in cli

- libindy/src/services/wallet/mod.rs
- libindy/src/services/wallet/storage/default/mod.rs
- libindy/src/services/wallet/wallet.rs
- wrappers/python/indy/error.py
> Changed behaviour of add_tags() and update_tags().

- wrappers/ios/libindy-pod/Podfile
> Updated Libindy pod version

- Specs/libindy/1.4.0-2/libindy.podspec.json
> Added 1.4.0-2 podspec file to support NonSecrets API

- Jenkinsfile.cd
> Fixed problem with version

- libindy/src/domain/credential.rs
- libindy/tests/interaction.rs
> Fixed credentials filtering bug

- libindy/src/services/wallet/mod.rs
> Double borrow fix

- doc/design/003-wallet-storage/README.md
- libindy/src/api/non_secrets.rs
- libindy/src/services/ledger/mod.rs
- libindy/src/services/wallet/mod.rs
- libindy/tests/anoncreds.rs
- libindy/tests/crypto.rs
- libindy/tests/non_secrets.rs
- libindy/tests/utils/non_secrets.rs
> Fixed mistakes in Libindy integration tests

- Jenkinsfile.cd
> Fixed libnullpay testing in cd pipeline

- libindy/src/commands/anoncreds/prover.rs
- libindy/src/commands/non_secrets.rs
- libindy/src/commands/payments.rs
- libindy/src/services/wallet/mod.rs
- libindy/tests/demo.rs
- libindy/tests/non_secrets.rs
- libindy/tests/pairwise.rs
- libindy/tests/payments.rs
> Fixed Libindy integration tests

- libindy/src/services/wallet/mod.rs
- libindy/src/services/wallet/storage/plugged/mod.rs
> Plugged wallet fixes

- Jenkinsfile.cd
- Jenkinsfile.ci
- doc/ubuntu-build.md
- libindy/Cargo.toml
- libindy/build.rs
- libindy/ci/ubuntu.dockerfile
- libindy/debian/control
> Sodium problem

- libindy/src/services/wallet/mod.rs
- libindy/src/services/wallet/storage/default/mod.rs
- libindy/src/services/wallet/storage/mod.rs
- libindy/src/services/wallet/storage/plugged/mod.rs
- libindy/src/services/wallet/wallet.rs
Signed-off-by: Janko Krstic <keichiri@protonmail.com>
> remove required mutable reference for storage operations

- libindy/src/services/wallet/mod.rs
- libindy/src/services/wallet/storage/default/mod.rs
- libindy/src/services/wallet/wallet.rs
Signed-off-by: Janko Krstic <keichiri@protonmail.com>
> wallet key rotation

- doc/mac-build.md
Signed-off-by: Nemanja Veskovic <nemanja.veskovic@gmail.com>
> Added missing dependency for zeromq on MacOS

- cli/README.md
> fix 404 to cli design

- libindy/src/domain/anoncreds/mod.rs
- libindy/src/services/crypto/mod.rs
- libindy/src/services/payments.rs
- libindy/src/services/pool/transaction_handler.rs
- libindy/src/utils/crypto/verkey_builder.rs
replaced e.g. ":" by ':' in e.g.  pattern matching
> use character instead of single character string

- libindy/src/commands/anoncreds/issuer.rs
- libindy/src/commands/anoncreds/tails.rs
- libindy/src/commands/did.rs
- libindy/src/commands/ledger.rs
- libindy/src/commands/payments.rs
- libindy/src/services/anoncreds/issuer.rs
- libindy/src/services/anoncreds/prover.rs
- libindy/src/services/anoncreds/verifier.rs
- libindy/src/services/ledger/mod.rs
- libindy/src/services/pool/catchup.rs
- libindy/src/services/pool/types.rs
- libindy/src/services/wallet/mod.rs
- libindy/src/services/wallet/wallet.rs
- libindy/src/utils/crypto/box_/sodium.rs
removed unused format! and replaced it by to_string()
> replaced unused format! by .to_string

- libindy/src/services/pool/catchup.rs
> Fix problem with txn count and failed node

- Jenkinsfile.cd
- ci/win-zip-and-upload.sh
- libindy/ci/ubuntu.dockerfile
> Publish windows zip archive from ubuntu node

- cli/src/commands/ledger.rs
- cli/src/commands/pool.rs
- cli/src/commands/wallet.rs
> Cli Pool Restart

- cli/src/commands/pool.rs
- cli/src/commands/wallet.rs
> Corrected error handling in CLI

- libindy/src/api/anoncreds.rs
- libindy/src/commands/anoncreds/issuer.rs
- libindy/src/domain/anoncreds/credential_definition.rs
- libindy/tests/anoncreds.rs
- libindy/tests/interaction.rs
- libindy/tests/utils/anoncreds.rs
- libindy/tests/utils/ledger.rs
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/anoncreds/Anoncreds.java
- wrappers/python/indy/anoncreds.py
> Set Config as optioanl in issuer_create_credential_def

- cli/src/commands/ledger.rs
- cli/src/commands/mod.rs
> Fixed parsing of outputs in CLI

- cli/src/commands/ledger.rs
- cli/src/commands/pool.rs
- cli/src/libindy/payment.rs
- libnullpay/src/services/config_ledger.rs
- libnullpay/tests/payments.rs
> Added parsing domain transaction responses with fees in CLI

- doc/design/009-wallet-export-import/README.md
> [DESIGN] Design of export/import

- cli/src/commands/payment_address.rs
- libindy/src/domain/ledger/request.rs
- libindy/src/services/ledger/mod.rs
- libindy/src/utils/crypto/chacha20poly1305_ietf/sodium.rs
- libindy/tests/ledger.rs
> Fixed protocol version

- wrappers/python/indy/did.py
Signed-off-by: Andrew Nikitin <andrew.nikitin@dsr-corporation.com>
> [Logging] fix logging parameter

- libindy/src/services/wallet/language.rs
Added support for expllicit "$and". 
Added a lot of tests for parsing of WQL.
> Improved WQL

- cli/src/libindy/mod.rs
- libindy/include/indy_mod.h
- libindy/src/api/mod.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyErrors.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ErrorCode.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/IndyException.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/payments/PaymentSourceDoesNotExistException.java
- wrappers/nodejs/codegen/api.json
- wrappers/python/indy/error.py
> Add new error code needed for plugin

- libnullpay/src/lib.rs
- libnullpay/src/payment_method.rs
- libnullpay/src/services/response_storage.rs
- libnullpay/tests/payments.rs
- libnullpay/tests/utils/wallet.rs
> Add utxo already spent error to libnullpay

- libindy/src/services/anoncreds/prover.rs
- libindy/tests/anoncreds.rs
> Corrected mapping old restriction format to wql

- libindy/include/indy_ledger.h
- libindy/src/api/ledger.rs
- libindy/src/services/ledger/mod.rs
- libindy/tests/ledger.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyLedger.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ledger/Ledger.java
- wrappers/nodejs/README.md
- wrappers/python/indy/ledger.py
> Updated build_get_txn to assept any number

- cli/src/commands/ledger.rs
> IS-568. Fixed get-attr help

- cli/src/commands/payment_address.rs
> Add new error message for payment commands in cli

- ci/android-zip-and-upload.sh
Signed-off-by: Mohammad Abdul Sami <faisal00813@gmail.com>
> Updated android publish script to use ssh instead of sftp

- Jenkinsfile.cd
> Corrected cd pipeline

- libindy/Cargo.lock
- libindy/Cargo.toml
> Updated indy-crypto version

- doc/getting-started/getting-started.md
Signed-off-by: Steve Jackson <steve.jackson@evernym.com>
> Corrected typos

- doc/how-tos/README.md
Signed-off-by: krw910 <krw910@gmail.com>
> Changed sentence in read.me for clarification

- libindy/src/services/crypto/mod.rs
- libindy/src/utils/crypto/sodium_type.rs
> Corrected verkey validation

- wrappers/ios/libindy-pod/Indy-demoTests/Test Utils/TestUtils.m
> Increased default timeout

- doc/design/002-anoncreds/README.md
- libindy/src/api/anoncreds.rs
- libindy/src/services/anoncreds/prover.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyAnoncreds.h
- wrappers/nodejs/README.md
- wrappers/python/indy/anoncreds.py
> Updated store_credential function to store rev_reg_id tag

- cli/src/commands/ledger.rs
> Corrected cli examples

- cli/src/commands/ledger.rs
> Ledger mint prepare issue

- cli/src/commands/pool.rs
- cli/src/libindy/pool.rs
- cli/src/main.rs
- doc/design/001-cli/README.md
> Added pool refresh command in Indy-Cli

- libindy/src/services/ledger/merkletree/mod.rs
> IS-708 Crash while consistency proof include empty 'proof' and invalid root_hash

- libindy/android.build.sh
- libindy/android.test.sh
- libindy/ci/setup.android.env.sh
- libnullpay/android.build.sh
- libnullpay/android.test.sh
Dependencies for android are now downloaded from repo.sovrin.org 
Replaced wget with curl
> Android optimised deps downloads

- libindy/src/services/wallet/storage/default/mod.rs
> Changed parameters of SQLite connection, for improving performance

- wrappers/python/indy/crypto.py
> Corrected returning types in crypto module python wrapper

- cli/src/commands/ledger.rs
- libindy/src/services/payments.rs
- libnullpay/src/payment_method.rs
- libnullpay/src/services/config_ledger.rs
- libnullpay/src/services/source_cache.rs
- libnullpay/src/utils/types.rs
> Fixed: Fee can be set below zero

- README.md
Signed-off-by: Susan Bradford <susan.bradford@evernym.com>
> marking old instructions as deprecated

- cli/src/commands/ledger.rs
> Improved error handling in get-validator-info

- libindy/src/utils/crypto/ed25519_sign/sodium.rs
- libindy/src/utils/crypto/mod.rs
Signed-off-by: lovesh harchandani <lovesh.bond@gmail.com>
> use constants from libsodium for sizes

- cli/src/commands/pool.rs
> Trivial change to error msg

- wrappers/dotnet/indy-sdk-dotnet/PaymentsApi/NativeMethods.cs
- wrappers/dotnet/indy-sdk-dotnet/PaymentsApi/PaymentMethod.cs
- wrappers/dotnet/indy-sdk-dotnet/PaymentsApi/Payments.cs
- wrappers/dotnet/indy-sdk-dotnet/WalletApi/NativeMethods.cs
- wrappers/dotnet/indy-sdk-dotnet/indy-sdk-dotnet.csproj
> Updated Payment API for dotnet wrapper

- libindy/src/services/pool/mod.rs
> Add safe variant for FS operations in indy_create_pool_ledger_config logic

- libindy/src/commands/anoncreds/issuer.rs
- libindy/src/commands/anoncreds/prover.rs
- libindy/src/commands/crypto.rs
- libindy/src/commands/did.rs
- libindy/src/commands/ledger.rs
- libindy/src/commands/pairwise.rs
- libindy/src/services/wallet/mod.rs
> Use DeserializeOwned trait instead of Deserialize in get_indy_object function

- Specs/libindy/1.6.4-739/libindy.podspec.json
- wrappers/ios/libindy-pod/Podfile
> Added 1.6.4-739 podspec

- doc/how-tos/rotate-key/python/rotate_key_on_the_ledger.py
- doc/how-tos/rotate-key/python/step2.py
- doc/how-tos/rotate-key/python/template.py
- libindy/src/services/pool/catchup.rs
- Changed template.py so that it uses the get_pool_genesis_txn_path
function instead of the hardcoded one.
- Updated rotate_key_on_the_ledger.py so it matches other files in the
same how-to guide (in particular the use of version 2 of the protocol)
and the way wallets are created.
Signed-off-by: fabienpe <fabienpe@users.noreply.github.com>
> Typos and small updates

- libindy/src/domain/ledger/attrib.rs
> indy-node and indy-plenum restrict endpoint to ip-address:port

- doc/ubuntu-build.md
This resolves Jira ticket IS-937.
Signed-off-by: Ken Ebert <ken@sovrin.org>
> Documentation improvement for indy-sdk/doc/ubuntu-build.md

- Jenkinsfile.cd
- Jenkinsfile.ci
> Try to fix VCX testing pipeline

- cli/src/commands/wallet.rs
> Forbidden detaching of opened wallet

- cli/src/commands/ledger.rs
- libindy/src/domain/ledger/constants.rs
- libindy/src/services/ledger/mod.rs
> IS-504 TGB role was removed

- libindy/src/api/pairwise.rs
- vcx/dummy-cloud-agent/src/actors/forward_agent.rs
- vcx/dummy-cloud-agent/src/app.rs
- vcx/dummy-cloud-agent/src/domain/mod.rs
- vcx/dummy-cloud-agent/src/domain/pairwise.rs
- vcx/dummy-cloud-agent/src/indy/did.rs
- vcx/dummy-cloud-agent/src/indy/logger.rs
- vcx/dummy-cloud-agent/src/indy/mod.rs
- vcx/dummy-cloud-agent/src/main.rs
- vcx/dummy-cloud-agent/src/utils/futures.rs
* Connect message handling implemented
* ftry! macro returned
* Indy wrapper for pairwise, log and did API
* Better error reporting, but still unfinished
* Minor fixes in libindy log messages
Signed-off-by: Vyacheslav Gudkov <vyacheslav.gudkov@dsr-company.com>
> Dummy Cloud Agent: Connect message handling implemented

- vcx/docs/migration.md
Signed-off-by: Mike Bailey <mike.bailey@evernym.com>
> Added info on changes to methods and attributes

- wrappers/dotnet/indy-sdk-dotnet/indy-sdk-dotnet.csproj
This PR updates the version of the project to match the latest RC and adds the generated documentation XML file to be part of the generated nuget package.
> [dotnet] Package version update, XML documentation

- vcx/dummy-cloud-agent/src/actors/forward_agent.rs
- vcx/dummy-cloud-agent/src/actors/forward_agent_connection.rs
- vcx/dummy-cloud-agent/src/domain/a2a.rs
- vcx/dummy-cloud-agent/src/domain/pairwise.rs
- vcx/dummy-cloud-agent/src/main.rs
- vcx/dummy-cloud-agent/src/utils/mod.rs
- vcx/dummy-cloud-agent/src/utils/tests.rs
- forward_agent restores connection actors on start 
- Fixed tests and test utils compilation
> Dummy Cloud Agent: forward_agent restores connection actors on start 

- vcx/dummy-cloud-agent/Cargo.lock
- vcx/dummy-cloud-agent/Cargo.toml
- vcx/dummy-cloud-agent/src/actors/forward_agent.rs
- vcx/dummy-cloud-agent/src/actors/forward_agent_connection.rs
- vcx/dummy-cloud-agent/src/main.rs
- vcx/dummy-cloud-agent/src/utils/tests.rs
* Test utils extended
* Added integration tests for connect and signup messages
> Dummy Cloud Agent: Integration testing boilerplate

- libindy/android.test.sh
Signed-off-by: Sergey Minaev <sergey.minaev@dsr-corporation.com>
> Verbose bash for running android tests.

- vcx/dummy-cloud-agent/src/app.rs
- vcx/libvcx/src/issuer_credential.rs
- vcx/libvcx/src/utils/devsetup.rs
- vcx/libvcx/src/utils/libindy/payments.rs
> Integrated Dummy Agent and Vcx

- vcx/wrappers/python3/demo/alice.py
- vcx/wrappers/python3/demo/faber.py
- vcx/wrappers/python3/tests/test_utils.py
- vcx/wrappers/python3/vcx/api/utils.py
> Updated configs in VCX python wrapper3

- vcx/docs/getting-started/getting-started.md
> Fixed VCX GSG

- Jenkinsfile.cd
- vcx/wrappers/python3/setup.py
- wrappers/python/setup.py
> Implemented common approach for python wrapper version setting

- vcx/wrappers/node/package.json
> Changed log level for vcx nodejs testing

- Jenkinsfile.cd
- Jenkinsfile.ci
- vcx/wrappers/node/test/helpers/test-constants.ts
> Extended timeout for VCX nodejs 'GC' tests

- Jenkinsfile.cd
> Commented VCX nodejs tests in CD pipeline

- wrappers/rust/Cargo.toml
> Fixed indy-sys version

- Jenkinsfile.cd
Signed-off-by: Sergey Minaev <sergey.minaev@dsr-corporation.com>
> Minor fix for CD.

- cli/src/utils/logger.rs
- libindy/tests/utils/crypto.rs
- libindy/tests/utils/logger.rs
- vcx/dummy-cloud-agent/src/indy/crypto.rs
- vcx/libvcx/src/utils/libindy/crypto.rs
- wrappers/rust/src/anoncreds.rs
- wrappers/rust/src/crypto.rs
- wrappers/rust/src/did.rs
- wrappers/rust/src/logger.rs
- wrappers/rust/src/pairwise.rs
- wrappers/rust/src/pool.rs
- wrappers/rust/src/wallet.rs
- wrappers/rust/tests/crypto.rs
> Corrected naming in Rust wrapper

- Jenkinsfile.cd
> Fixed android testing in CD pipeline

- vcx/libvcx/Cargo.lock
- vcx/libvcx/Cargo.toml
- vcx/libvcx/src/api/logger.rs
- vcx/libvcx/src/utils/libindy/logger.rs
- vcx/libvcx/src/utils/libindy/mod.rs
- vcx/libvcx/src/utils/logger.rs
>  Pipe vcx and libindy logs

- cli/Cargo.lock
- libindy/Cargo.lock
- libindy/src/services/pool/mod.rs
- libindy/src/services/pool/request_handler.rs
- libindy/src/services/pool/state_proof/mod.rs
- libindy/tests/utils/payments.rs
- libindy/tests/utils/wallet.rs
- libnullpay/Cargo.lock
- libnullpay/src/libindy/payments.rs
- libnullpay/src/payment_method.rs
- vcx/libvcx/Cargo.lock
- vcx/libvcx/src/api/mod.rs
- wrappers/rust/Cargo.toml
- wrappers/rust/indy-sys/Cargo.toml
- wrappers/rust/indy-sys/src/lib.rs
- wrappers/rust/src/utils/callbacks.rs
> Aligned usages of C-types across Indy

- doc/cred-revocation.md
Signed-off-by: Stephen Felt <steptan@gmail.com>
> Minor document corrections and clarifications

- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/LibVcx.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibIndy.java
> VCX Java logging

- vcx/wrappers/java/build.gradle
- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/issuer/IssuerApi.java
> Temporary Fix of issuerCreateCredential function in VCX Java wrapper 

- Jenkinsfile.ci
> Added MacOS Libvccx testing to CI pipeline

- doc/how-tos/write-did-and-query-verkey/README.md
- doc/how-tos/write-did-and-query-verkey/cs/README.md
- doc/how-tos/write-did-and-query-verkey/java/README.md
- doc/how-tos/write-did-and-query-verkey/nodejs/README.md
- doc/how-tos/write-did-and-query-verkey/nodejs/colors.js
- doc/how-tos/write-did-and-query-verkey/nodejs/package.json
- doc/how-tos/write-did-and-query-verkey/nodejs/step2.js
- doc/how-tos/write-did-and-query-verkey/nodejs/step3.js
- doc/how-tos/write-did-and-query-verkey/nodejs/step4.js
- doc/how-tos/write-did-and-query-verkey/nodejs/step5.js
- doc/how-tos/write-did-and-query-verkey/nodejs/template.js
- doc/how-tos/write-did-and-query-verkey/nodejs/util.js
- doc/how-tos/write-did-and-query-verkey/nodejs/writeDidAndQueryVerkey.js
- doc/how-tos/write-did-and-query-verkey/python/README.md
Add NodeJs edition for `doc/how-tos/write-did-and-query-verkey`
Signed-off-by: Xavier NOPRE <xnopre@gmail.com>
> Doc/how-tos/write-did-and-query-verkey : add NodeJs edition

- wrappers/rust/Cargo.toml
> Set strict dependency version for backtrace crate

- Jenkinsfile.cd
- Jenkinsfile.ci
- libindy/ci/amazon.dockerfile
- libindy/ci/ubuntu.dockerfile
- vcx/ci/libindy.dockerfile
- vcx/ci/libvcx.dockerfile
- vcx/ci/ubuntu.dockerfile
- vcx/libvcx/build_scripts/ios/mac/mac.01.libindy.setup.sh
- vcx/wrappers/java/ci/android.dockerfile
> Upgrading to rust 1.31

- Jenkinsfile.cd
> Fixed versioning for vcx packages in CD Pipeline

- cli/src/main.rs
- vcx/wrappers/java/README.md
- vcx/wrappers/python3/README.md
- wrappers/java/README.md
- wrappers/python/README.md
> Corrected Logging instruction for wrappers READ.me.

- wrappers/rust/Cargo.toml
> Removed strict version for rust backtrace crate

- wrappers/python/indy/__init__.py
Signed-off-by: Dan Farnsworth <absltkaos@gmail.com>
> IS-1115 - Adjust python wrapper namespacing

- Jenkinsfile.cd
- Jenkinsfile.ci
> Changed pytest version for VCX python wrapper testing

- doc/rhel-build.md
- doc/ubuntu-build.md
- doc/windows-build.md
- libindy/ci/amazon.dockerfile
- libindy/ci/ubuntu.dockerfile
> Updated url to libsodium installation

- cli/src/commands/ledger.rs
- libindy/include/indy_ledger.h
- libindy/src/api/anoncreds.rs
- libindy/src/api/ledger.rs
- libindy/src/commands/anoncreds/issuer.rs
- libindy/src/domain/anoncreds/schema.rs
- libindy/src/services/ledger/mod.rs
- libindy/tests/anoncreds.rs
- vcx/libvcx/src/api/schema.rs
- vcx/wrappers/node/src/api/schema.ts
- vcx/wrappers/python3/vcx/api/schema.py
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyAnoncreds.h
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyLedger.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/anoncreds/Anoncreds.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ledger/Ledger.java
- wrappers/nodejs/README.md
- wrappers/python/indy/anoncreds.py
- wrappers/python/indy/ledger.py
- wrappers/rust/src/anoncreds.rs
- wrappers/rust/src/ledger.rs
> Added restriction for the max acceptable number of schema attributes

- libindy/Cargo.lock
- libindy/Cargo.toml
- libindy/src/commands/crypto.rs
- libindy/src/domain/crypto/key.rs
- libindy/src/lib.rs
- libindy/src/services/wallet/wallet.rs
- libindy/src/utils/crypto/memzero/sodium.rs
- libindy/src/utils/crypto/mod.rs
- libindy/src/utils/crypto/randombytes/sodium.rs
- libindy/src/utils/memzeroize.rs
- libindy/src/utils/mod.rs
- libindy/tests/utils/mod.rs
Signed-off-by: Michael Lodder <redmike7@gmail.com>
> Safely zero keys and prevent compiler optimization of zeroing

- vcx/libvcx/src/issuer_credential.rs
> fixes agency push notification for a cred offer

- samples/java/README.md
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibIndy.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/crypto/Crypto.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/crypto/PackUnpackMessageTest.java
The implementation follows the pattern of authCrypt.   The apis are very similar.
> IS 1160 Java updates for pack/unpack API

- CHANGELOG.md
> Add note for freshness issues

- README.md
Signed-off-by: bryant <blhagadorn@gmail.com>
> Changed link for builds, release workflow, and others

- libnullpay/src/lib.rs
- libnullpay/src/utils/logger.rs
This PR is to get an artifact to the vcx team with logging disabled in libnullpay
> Hotfix for nullpay logging on mobile platforms

- CHANGELOG.md
- libindy/debian/changelog
> Add changelogs

- wrappers/java/src/test/java/org/hyperledger/indy/sdk/utils/PoolUtils.java
> Extended timeout for java tests

- vcx/libvcx/src/utils/httpclient.rs
Signed-off-by: Douglas Wightman <douglas.wightman@evernym.com>
> [VCX] increase http client timeout to default long_timeout (VE-914)

- CHANGELOG.md
- cli/README.md
- docs/migration-guides/migration-guide-1.3.0-1.4.0.md
- docs/migration-guides/migration-guide-1.4.0-1.5.0.md
- experimental/plugins/postgres_storage/README.md
FIX: Doc link was pointed to doc instead of docs.
> fix doc(s) hyperlinks

- libindy/tests/interaction.rs
- vcx/dummy-cloud-agent/Cargo.lock
> Fixed freshness problem in libindy interaction tests

- libindy/src/commands/crypto.rs
> Decreased log level in crypto commands

- libindy/src/api/anoncreds.rs
- wrappers/dotnet/indy-sdk-dotnet/AnonCredsApi/AnonCreds.cs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyAnoncreds.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/anoncreds/Anoncreds.java
- wrappers/nodejs/README.md
- wrappers/python/indy/anoncreds.py
- wrappers/rust/src/anoncreds.rs
> Libindy documentation fixes

- vcx/wrappers/python3/demo/README.txt
Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>
Updated readme to include description of updated python alice/faber scripts
> Updated vcx python demo readme

- Jenkinsfile.cd
- Jenkinsfile.ci
- ci/ios-build.sh
- wrappers/ios/README.md
> macos openssl 1.0.2q

- vcx/README.md
> Updated vcx readme to reflect windows installation

- libindy/src/services/wallet/mod.rs
> Better error message for wallet storage errors

- docs/contributors/release-workflow.md
- samples/java/pom.xml
- vcx/wrappers/java/README.md
- wrappers/java/README.md
> Updated java wrappers documentation to point on new artifacts location

- ci/ios-build.sh
> Set OPENSSL_DIR only if it isn't set yet in ios-build.sh

- libindy/src/utils/crypto/signature_serializer.rs
- libindy/tests/ledger.rs
> IS-1158 Corrected requests signature serialization

- libindy/include/indy_crypto.h
- libindy/src/api/crypto.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyCrypto.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/crypto/Crypto.java
- wrappers/nodejs/README.md
- wrappers/python/indy/crypto.py
- wrappers/rust/src/crypto.rs
> Removed Deprecation warning from indy anon crypt/decrypt functions

- vcx/wrappers/python3/demo/alice.py
- vcx/wrappers/python3/demo/demo_utils.py
- vcx/wrappers/python3/demo/faber.py
Signed-off-by: Patrik Stas <patrik.stas@absa.co.za>
> Make python VCX wrapper demo work out of the box on OSX.

- Jenkinsfile.cd
- vcx/wrappers/node/package.json
> IS-1210 Fixed packaging of vcx nodejs wrapper

- Jenkinsfile.cd
> Nodejs cd pipeline fix

- Jenkinsfile.cd
- Jenkinsfile.ci
> Disabled testing on amazon

- cli/src/commands/ledger.rs
- libindy/src/api/ledger.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyLedger.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ledger/Ledger.java
- wrappers/nodejs/README.md
- wrappers/python/indy/ledger.py
> Updated documentation for AUTH_RULE builder

- vcx/wrappers/ios/vcx/utils/NSError+VcxError.m
- vcx/wrappers/ios/vcx/vcx.framework/Headers/libvcx.h
> Corrected getting error details for vcx ios wrapper

- wrappers/rust/Cargo.toml
> fix repo link

- docs/how-tos/issue-credential/python/README.md
> Fix broken hyperlink

- libindy/src/services/pool/pool.rs
- libindy/src/services/pool/request_handler.rs
> [IS-1085] Make libindy call ledger two times on single request on first time

- Jenkinsfile.cd
> IS-1139:  Updated CLI to depend on strict libindy version

- docs/getting-started/getting-started.dockerfile
- libindy/src/api/anoncreds.rs
- samples/java/pom.xml
- samples/python/setup.py
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyAnoncreds.h
- wrappers/nodejs/README.md
- wrappers/python/indy/anoncreds.py
> IS-1139: Updated libindy for samples. Corrected some links

- libindy/src/services/pool/mod.rs
- libindy/src/services/pool/request_handler.rs
> Enable freshness

- libindy/src/services/pool/request_handler.rs
> Fix double request

- Jenkinsfile.cd
> Bugfix: Corrected moving RC artifacts to Stable

- Specs/libindy/1.8.1/libindy.podspec.json
- Specs/libindy/1.8.2/libindy.podspec.json
> Bugfix: Corrected links to libindy in podspec files

- ci/indy-pool.dockerfile
> Removed installation of indy-anoncreds from indy-pool.dockerfile

- libindy/src/services/wallet/encryption.rs
- libindy/src/services/wallet/language.rs
> replace single-char string constant by char constant

- libindy/src/domain/anoncreds/credential_definition.rs
- libindy/src/domain/anoncreds/revocation_registry_definition.rs
- libindy/src/domain/anoncreds/schema.rs
- libindy/src/domain/ledger/request.rs
- libindy/src/services/anoncreds/prover.rs
- libindy/src/services/crypto/mod.rs
- libindy/src/services/pool/events.rs
> remove unneeded static for const

- libindy/src/commands/crypto.rs
- libindy/src/commands/did.rs
- libindy/src/services/ledger/merkletree/merkletree.rs
- libindy/src/services/ledger/merkletree/mod.rs
- libindy/src/services/pool/catchup.rs
- libindy/src/services/pool/mod.rs
- libindy/src/services/pool/state_proof/node.rs
- libindy/src/services/wallet/storage/default/mod.rs
> remove unneeded return statements

- Jenkinsfile.cd
- ci/win-zip-and-upload.sh
> Updated Liibndy Windows  package to contain libindy.dll.lib

- libindy/src/api/crypto.rs
- libindy/src/commands/crypto.rs
- libindy/tests/crypto.rs
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/crypto/PackUnpackMessageTest.java
- wrappers/python/tests/crypto/test_pack_message.py
> check pack_message parameters early on api level

- libindy/src/domain/ledger/constants.rs
- wrappers/ios/libindy-pod/Indy-demoTests/Case Tests/Ledger/LedgerBuildRequest.mm
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/AcceptanceMechanismRequestTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/AuthorAgreementRequestTest.java
- wrappers/nodejs/test/ledger.js
- wrappers/python/tests/ledger/test_build_acceptance_mechanism_request.py
- wrappers/python/tests/ledger/test_build_txn_author_agreement_request.py
Signed-off-by: Sergey Khoroshavin <sergey.khoroshavin@dsr-corporation.com>
> Update TAA-related transaction codes

- libnullpay/src/services/payment_ledger.rs
- libnullpay/src/utils/sequence.rs
- libnullpay/tests/utils/sequence.rs
> ATOMIC_USIZE_INIT is deprecated

- libindy/src/commands/anoncreds/issuer.rs
- libindy/src/domain/anoncreds/credential_definition.rs
- libindy/src/domain/anoncreds/revocation_registry_definition.rs
- libindy/src/domain/anoncreds/schema.rs
- libindy/src/domain/wallet/mod.rs
- libindy/src/services/ledger/merkletree/mod.rs
- libindy/src/services/pool/catchup.rs
- libindy/src/services/pool/events.rs
- libindy/src/services/pool/networker.rs
- libindy/src/services/pool/state_proof/mod.rs
- libindy/src/services/pool/state_proof/node.rs
- libindy/src/services/pool/types.rs
- libindy/src/services/wallet/encryption.rs
- libindy/src/services/wallet/storage/default/mod.rs
- libindy/src/services/wallet/storage/default/query.rs
- libindy/src/services/wallet/storage/plugged/mod.rs
- libindy/src/utils/crypto/chacha20poly1305_ietf/sodium.rs
> make clippy happy

- libindy/src/commands/anoncreds/prover.rs
- libindy/src/services/wallet/mod.rs
- libindy/src/services/wallet/storage/plugged/mod.rs
removing some more Clippy warnings
> variable does not need to be mutable

- libindy/src/services/pool/state_proof/mod.rs
Signed-off-by: Sergey Khoroshavin <skhoroshavin@gmail.com>
> Fix bug in GET_TAA state proof validation

- cli/src/commands/ledger.rs
- cli/src/commands/pool.rs
- cli/src/libindy/ledger.rs
- cli/src/libindy/payment.rs
- cli/src/main.rs
- docs/design/001-cli/README.md
- libindy/src/api/ledger.rs
> IS-1255:  Indy-Cli: commands to set txn agreement and acceptance mechanisms

- Jenkinsfile.cd
> IS-6: Corrected version building

- vcx/libvcx/src/utils/libindy/payments.rs
> Temporary disabled functionality of getting auth rule  for VCX

- cli/src/commands/ledger.rs
- cli/src/libindy/ledger.rs
- libindy/include/indy_ledger.h
- libindy/src/api/ledger.rs
- libindy/src/commands/ledger.rs
- libindy/src/services/ledger/mod.rs
- libindy/tests/ledger.rs
- libindy/tests/utils/ledger.rs
- vcx/libvcx/src/utils/libindy/ledger.rs
- wrappers/ios/libindy-pod/Indy-demoTests/Case Tests/Ledger/LedgerBuildRequest.mm
- wrappers/ios/libindy-pod/Indy-demoTests/Test Utils/LedgerUtils.h
- wrappers/ios/libindy-pod/Indy-demoTests/Test Utils/LedgerUtils.mm
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyLedger.h
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyLedger.mm
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibIndy.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ledger/Ledger.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/AcceptanceMechanismRequestTest.java
- wrappers/nodejs/README.md
- wrappers/nodejs/src/index.js
- wrappers/nodejs/src/indy.cc
- wrappers/nodejs/test/ledger.js
- wrappers/python/indy/ledger.py
- wrappers/python/tests/ledger/test_build_acceptance_mechanisms_request.py
- wrappers/rust/indy-sys/src/ledger.rs
- wrappers/rust/src/ledger.rs
> IS-1256: Renamed functions

- ci/indy-pool.dockerfile
- libindy/src/services/pool/events.rs
- libindy/src/services/pool/request_handler.rs
- libindy/src/services/pool/state_proof/mod.rs
- libindy/tests/ledger.rs
> Fixed state proof validation

- wrappers/rust/src/anoncreds.rs
- wrappers/rust/src/blob_storage.rs
- wrappers/rust/src/cache.rs
- wrappers/rust/src/crypto.rs
- wrappers/rust/src/did.rs
- wrappers/rust/src/ledger.rs
- wrappers/rust/src/lib.rs
- wrappers/rust/src/pairwise.rs
- wrappers/rust/src/payments.rs
- wrappers/rust/src/pool.rs
- wrappers/rust/src/wallet.rs
> Forwarded data types in Rust wrapper

- ci/indy-pool.dockerfile
- libindy/src/domain/ledger/auth_rule.rs
- libindy/src/services/ledger/mod.rs
- vcx/libvcx/src/utils/libindy/ledger.rs
> Support Forbidden constraint type

- Specs/libindy/1.9.0/libindy.podspec.json
Signed-off-by: Sergey Minaev <sergey.minaev@dsr-corporation.com>
> Fix libindy podspec for 1.9.0

- libindy/src/services/pool/state_proof/mod.rs
> Corrected state proof verification for get auth rule request

- libindy/src/services/anoncreds/prover.rs
- libindy/src/services/anoncreds/verifier.rs
- libindy/src/services/ledger/mod.rs
- libindy/src/services/pool/merkle_tree_factory.rs
- libindy/src/services/pool/networker.rs
- libindy/src/services/pool/request_handler.rs
> remove static lifetime from const

- libindy/Cargo.lock
- libindy/Cargo.toml
> new version owning_ref 0.4

- samples/nodejs/README.md
> IS-1230: Added libindy installation section to nodejs sample readme

- wrappers/dotnet/indy-sdk-dotnet/LedgerApi/Ledger.cs
- wrappers/dotnet/indy-sdk-dotnet/LedgerApi/NativeMethods.cs
- wrappers/dotnet/indy-sdk-dotnet/PaymentsApi/NativeMethods.cs
- wrappers/dotnet/indy-sdk-dotnet/PaymentsApi/Payments.cs
- wrappers/dotnet/indy-sdk-dotnet/indy-sdk-dotnet.csproj
> [dotnet wrapper] Updated Payment and Ledger API

- wrappers/java/pom.xml
> Updated indy java pom.xml to use stable slfj version

- cli/src/command_executor.rs
- cli/src/commands/ledger.rs
- cli/src/commands/pool.rs
- cli/src/main.rs
> IS-1300 Answering "yes" to prompts when using Indy CLI batch automation

- libindy/src/api/anoncreds.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyAnoncreds.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/anoncreds/Anoncreds.java
- wrappers/nodejs/README.md
- wrappers/python/indy/anoncreds.py
- wrappers/rust/src/anoncreds.rs
> IS-1279: Improved anoncreds documentation

- vcx/libvcx/src/utils/libindy/payments.rs
> IS-1275: Enable fees determining based on GET_AUTH_RULES in VCX

- README.md
- ci/indy-pool.dockerfile
- cli/README.md
- cli/cli.dockerfile
- docs/getting-started/getting-started.dockerfile
- libnullpay/README.md
- vcx/README.md
- vcx/ci/libindy.dockerfile
- vcx/ci/ubuntu.dockerfile
> Change GPG key

- cli/src/commands/ledger.rs
> CLI: Check that acceptance mechanism type isn't empty

- cli/src/command_executor.rs
- cli/src/main.rs
- cli/src/utils/environment.rs
- cli/src/utils/file.rs
- cli/src/utils/history.rs
- cli/src/utils/mod.rs
> IS-1307: Indy CLI persist command history between sessions

- libindy/src/services/crypto/mod.rs
> IS-1266: error message for unexpected length of did

- ci/indy-pool.dockerfile
- libindy/include/indy_ledger.h
- libindy/src/api/ledger.rs
- libindy/src/services/ledger/mod.rs
- libindy/tests/ledger.rs
- libindy/tests/payments.rs
- wrappers/ios/libindy-pod/Indy-demoTests/Case Tests/Ledger/LedgerBuildRequest.mm
- wrappers/ios/libindy-pod/Indy-demoTests/Case Tests/Payment/PaymentHighCases.mm
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyLedger.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ledger/Ledger.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/AppendAuthorAgreementAcceptanceToRequestTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/payment/PreparePaymentExtraWithAcceptanceDataTest.java
- wrappers/nodejs/README.md
- wrappers/nodejs/test/ledger.js
- wrappers/nodejs/test/payments.js
- wrappers/python/indy/ledger.py
- wrappers/python/tests/ledger/text_append_author_agreement_meta.py
- wrappers/python/tests/payment/test_prepare_payment_extra_with_acceptance_data.py
- wrappers/rust/src/ledger.rs
> IS-1298: Only return the date (not time) for the TAA acceptance

- libindy/src/services/pool/state_proof/mod.rs
> INDY-2158: Fixed state proof verification for GET_REV_DELTA

- cli/src/commands/ledger.rs
> TAA mustn't be set for `set fees` transaction

- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/LibVcx.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibIndy.java
> IS-1229 Fix for "Android Crash upon  logging"

- cli/src/main.rs
> IS-1321: CLI persist all command

- wrappers/dotnet/indy-sdk-dotnet/AnonCredsApi/AnonCreds.cs
- wrappers/dotnet/indy-sdk-dotnet/AnonCredsApi/NativeMethods.cs
> [dotnet wrapper] Add credential deletion wrapper

- libindy/src/services/pool/state_proof/mod.rs
- libindy/src/services/pool/types.rs
> ST-604 -- Change structures

- Jenkinsfile.cd
- Jenkinsfile.ci
> ignore failure of docker -rm during cleanup

- libindy/include/indy_payment.h
- libindy/src/api/payments.rs
- libindy/src/domain/ledger/auth_rule.rs
- libindy/src/services/ledger/mod.rs
- libindy/src/services/payments.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyPayment.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/payments/Payments.java
- wrappers/nodejs/README.md
- wrappers/python/indy/payment.py
- wrappers/rust/src/payments.rs
> `role` must be an optional  within constraint

- cli/README.md
- docs/configuration.md
> IS-1305 Initial version of configuration document

- libindy/src/api/anoncreds.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyAnoncreds.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/anoncreds/Anoncreds.java
- wrappers/nodejs/README.md
- wrappers/python/indy/anoncreds.py
- wrappers/rust/src/anoncreds.rs
> IS-1228: Documented workaround for `Permission Denied` error

- cli/src/commands/ledger.rs
- libindy/include/indy_ledger.h
- libindy/include/indy_payment.h
- libindy/src/api/ledger.rs
- libindy/src/api/payments.rs
- libindy/src/domain/ledger/auth_rule.rs
- libindy/src/services/ledger/mod.rs
- libindy/src/services/payments.rs
- libindy/tests/ledger.rs
- vcx/libvcx/src/utils/libindy/payments.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyLedger.h
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyPayment.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ledger/Ledger.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/payments/Payments.java
- wrappers/nodejs/README.md
- wrappers/python/indy/ledger.py
- wrappers/python/indy/payment.py
- wrappers/rust/src/ledger.rs
- wrappers/rust/src/payments.rs
> IS-1329: Supported `off_ledger_endorser` flag for auth rules

- ci/indy-pool.dockerfile
- docs/configuration.md
- libindy/include/indy_ledger.h
- libindy/src/api/ledger.rs
- libindy/src/commands/ledger.rs
- libindy/src/domain/ledger/request.rs
- libindy/tests/ledger.rs
- libindy/tests/utils/ledger.rs
- libindy/tests/utils/mod.rs
- wrappers/nodejs/test/ledger.js
- wrappers/rust/indy-sys/src/ledger.rs
- wrappers/rust/src/ledger.rs
> IS-1325: Supported `endorser` field for transactions

- libindy/src/services/pool/state_proof/node.rs
> Fix state proof on leaf

- libindy/src/api/payments_v2.rs
- libindy/src/commands/payments.rs
- libindy/src/services/payments.rs
- libindy/tests/utils/payments.rs
- wrappers/rust/src/payments.rs
> Fix inner types in libindy

- Jenkinsfile.cd
- Jenkinsfile.ci
> Execute CI/CD cargo test with 1 parallel job

- libindy/src/services/wallet/mod.rs
- libindy/src/services/wallet/storage/default/mod.rs
- libindy/tests/pool.rs
cleanup directories created during tests
> Cleanup Tests Directories

- cli/src/commands/ledger.rs
- cli/src/commands/payment_address.rs
> IS-1341 and IS-1342 fixes

- docs/configuration.md
> IS-1243 - Updated configuration document to reflect pool refreshing and CLI  TAA

- libindy/tests/pool.rs
> ignore error in test

- cli/src/commands/ledger.rs
- cli/src/libindy/ledger.rs
- cli/src/main.rs
- docs/design/001-cli/README.md
> IS-1337 Make Indy-CLI support endorser

- libindy/src/commands/crypto.rs
> add size hint

- libindy/src/domain/anoncreds/schema.rs
> use iter to create new map with other Item type

- docs/configuration.md
- libindy/src/api/pool.rs
- libindy/src/domain/pool.rs
- libindy/src/services/pool/mod.rs
- libindy/src/services/pool/pool.rs
- libindy/src/services/pool/request_handler.rs
- libindy/tests/pool.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyPool.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/pool/Pool.java
- wrappers/nodejs/README.md
- wrappers/python/indy/pool.py
- wrappers/rust/src/pool.rs
> Pool: Configure the number of nodes to send read requests

- libindy/src/services/anoncreds/prover.rs
- libindy/src/services/pool/networker.rs
- libindy/src/services/pool/state_proof/mod.rs
- libindy/src/services/pool/state_proof/node.rs
- libindy/src/services/wallet/language.rs
- libindy/src/services/wallet/query_encryption.rs
- libindy/src/services/wallet/storage/plugged/mod.rs
use Vec::with_capacity instead of Vec::new
saves some memory and probably reallocation
> Vec with capacity

- libindy/tests/crypto.rs
- libindy/tests/payments.rs
- libindy/tests/utils/did.rs
- libindy/tests/utils/mod.rs
- libindy/tests/utils/wallet.rs
> Libindy tests refactoring. Setup/Drop

- cli/src/commands/pool.rs
> IS-1352: CLI: support number nodes to send read request

- Jenkinsfile.cd
- Jenkinsfile.ci
- libindy/tests/demo.rs
- libindy/tests/interaction.rs
- libindy/tests/wallet.rs
> Liibndy test cleaning

- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/credentialDef/CredentialDefApi.java
- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/issuer/IssuerApi.java
- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/schema/SchemaApi.java
> VCX: Fix checks in java wrapper

- libindy/src/services/pool/pool.rs
> IS-1356: Pool refresh doesn't throw timeout error in CLI

- Jenkinsfile.cd
- Jenkinsfile.ci
- libindy/ci/ubuntu18.dockerfile
> IS-1345: Run full testing on Ubuntu 18

- libindy/src/services/pool/mod.rs
- libindy/src/services/pool/pool.rs
- libindy/src/services/pool/request_handler.rs
- libindy/src/services/pool/state_proof/mod.rs
new type `type Nodes = HashMap<String, Option<VerKey>>`
> type Nodes = HashMap<String, Option<VerKey>>

- experimental/plugins/postgres_storage/Cargo.toml
- libindy/Cargo.lock
- libindy/Cargo.toml
- libindy/src/utils/crypto/pwhash_argon2i13/sodium.rs
> Remove dependency on errno

- libindy/src/api/anoncreds.rs
- libindy/tests/anoncreds_demos.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyAnoncreds.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/anoncreds/Anoncreds.java
- wrappers/python/indy/anoncreds.py
> Added test on different predicate types. Inproved anoncreds related documentation

- Jenkinsfile.cd
> CD Pipeline - test wrappers on ubuntu 18

- Jenkinsfile.cd
> CD Pipeline - use python6

- Jenkinsfile.cd
- Jenkinsfile.ci
- README.md
- ci/macos-zip-and-upload.sh
- cli/README.md
- docs/build-guides/rhel-build.md
- libindy/Cargo.lock
- libindy/tests/interaction.rs
- vcx/README.md
- wrappers/ios/README.md
> IS-533 MacOS improvements

- vcx/README.md
Signed-off-by: Corin Kochenower <corin.kochenower@evernym.com>
> Correct URL to MacOS build guide

- libindy/src/domain/ledger/request.rs
> Request identifier can be optional

- libindy/src/domain/ledger/request.rs
- libindy/tests/utils/pool.rs
> utils/pool.rs get_req_id was unused. Move it and use it

- vcx/dummy-cloud-agent/README.md
Signed-off-by: Patrik Stas <patrik.stas@absa.co.za>
> Add readme about dummy cloud agency actors and messages

- docs/how-tos/how-to-add-a-new-API-call.md
> IS-1372: How to add new API call: Testing section and complex commands

- libindy/src/services/pool/state_proof/mod.rs
> IS-1383 - fix GET_TXN state proof parsing

- libindy/tests/utils/anoncreds.rs
- libindy/tests/utils/ledger.rs
- libindy/tests/utils/non_secrets.rs
- libindy/tests/utils/payments.rs
> ONCE_INIT is deprecated

- libindy/src/domain/anoncreds/credential_offer.rs
- libindy/src/services/anoncreds/helpers.rs
- libindy/src/utils/qualifier.rs
> Corrected REGEX for Fully-Qualified identifiers

- libindy/src/services/pool/state_proof/mod.rs
> IS-1383 - fix state proof parsing again

- wrappers/java/src/test/java/org/hyperledger/indy/sdk/IndyIntegrationTest.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/interaction/AnoncredsVerifyProofAfterCredentialRevokeTest.java
> IS-1368: Verifying proof after credential revocation results in true (added test to run on CI)

- cli/src/commands/ledger.rs
- wrappers/rust/src/logger.rs
fix some clippy warnings to get https://github.com/hyperledger/indy-sdk/pull/1877 to build
> Clippy warnings fixes

- CHANGELOG.md
- docs/migration-guides/migration-guide-1.11.0-1.12.0.md
- libindy/debian/changelog
- libindy/src/api/anoncreds.rs
- libindy/src/domain/anoncreds/credential_definition.rs
- libindy/src/domain/anoncreds/credential_request.rs
- libindy/src/domain/anoncreds/revocation_registry_definition.rs
- libindy/src/domain/anoncreds/schema.rs
- libindy/src/services/anoncreds/helpers.rs
- libindy/tests/anoncreds.rs
- vcx/libvcx/debian/changelog
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyAnoncreds.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/anoncreds/Anoncreds.java
- wrappers/nodejs/README.md
- wrappers/python/indy/anoncreds.py
- wrappers/rust/src/anoncreds.rs
> Rc 1.12.0 Updates

- docs/configuration.md
- docs/how-tos/fully-qualified-did-support.md
- docs/how-tos/transaction-author-agreement.md
- libindy/include/indy_ledger.h
- libindy/src/api/ledger.rs
- libindy/src/api/payments.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyLedger.h
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyPayment.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ledger/Ledger.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/payments/Payments.java
- wrappers/nodejs/README.md
- wrappers/python/indy/ledger.py
- wrappers/python/indy/payment.py
- wrappers/rust/src/ledger.rs
- wrappers/rust/src/payments.rs
> Improved documentation regarding TAA and Fully-Qualified support

- wrappers/dotnet/indy-sdk-dotnet/AnonCredsApi/AnonCreds.cs
- wrappers/dotnet/indy-sdk-dotnet/AnonCredsApi/NativeMethods.cs
- wrappers/dotnet/indy-sdk-dotnet/DidApi/Did.cs
- wrappers/dotnet/indy-sdk-dotnet/DidApi/NativeMethods.cs
- wrappers/dotnet/indy-sdk-dotnet/LedgerApi/Ledger.cs
- wrappers/dotnet/indy-sdk-dotnet/LedgerApi/NativeMethods.cs
- wrappers/dotnet/indy-sdk-dotnet/PaymentsApi/NativeMethods.cs
- wrappers/dotnet/indy-sdk-dotnet/PaymentsApi/Payments.cs
- wrappers/dotnet/indy-sdk-dotnet/indy-sdk-dotnet.csproj
- AnonCreds API - Added GenarateNonce, ToUnqualified, added Roate Credential Definition Start/Apply wrappers
- Did API - Add Qualify Did wrapper 
- Ledger API - Add AppendRequestEndorser wrapper
- Payment API - Add Sign/Verify with address, GrtRequestInfo
- Package version bump to 1.11.1
> [dotnet wrapper] Update wrapper to be in line with 1.11.1

- libindy/src/domain/anoncreds/credential_definition.rs
> unneeded return statement

- CHANGELOG.md
- libindy/debian/changelog
> IS-1361 - Updated changelog to set on correct release date

- libindy/src/commands/anoncreds/prover.rs
- libindy/src/services/pool/request_handler.rs
- libindy/src/services/pool/state_proof/mod.rs
- libindy/src/services/wallet/storage/plugged/mod.rs
- libindy/tests/utils/constants.rs
> use with_capacity if possible

- Jenkinsfile.cd
- Jenkinsfile.ci
- libindy/ci/centos.dockerfile
- libindy/ci/ubuntu.dockerfile
- libindy/ci/ubuntu18.dockerfile
- libindy/src/services/pool/pool.rs
- libindy/tests/anoncreds_demos.rs
- vcx/ci/libindy.dockerfile
- vcx/ci/libvcx.dockerfile
- vcx/ci/ubuntu.dockerfile
- vcx/libvcx/build_scripts/ios/mac/mac.01.libindy.setup.sh
- vcx/wrappers/java/ci/android.dockerfile
with async and wait.
Now wrappers/rust should be async-ified
ps: move tests/anoncreds_demos.rs	tests/demo.rs to wrappers/rust and rewrite, please
> Rust new version

- wrappers/java/README.md
Signed-off-by: Nemanja Patrnogic <3052405+donqui@users.noreply.github.com>
> Remove an unneccesary comment

- Jenkinsfile.cd
- Jenkinsfile.ci
- libindy/ci/ubuntu18.dockerfile
1. Revert "Temporary disable pipelines for MacOS and iOS."
2. Temporary debug steps in CI
> Minor CI fixes

- docs/configuration.md
> IS-1388: Extend configuration doc with VCX info

- docs/build-guides/rhel-build.md
- docs/build-guides/ubuntu-build.md
- libindy/ci/centos.dockerfile
- libindy/ci/ubuntu.dockerfile
> Out of tickets -- fix libsodium url inside docker images.

- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/NymRequestsTest.java
> Hotfix: fixing resubmissions in Java.

- libindy/src/api/anoncreds.rs
- vcx/libvcx/src/api/issuer_credential.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyAnoncreds.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/anoncreds/Anoncreds.java
- wrappers/nodejs/README.md
- wrappers/python/indy/anoncreds.py
- wrappers/rust/src/anoncreds.rs
> IS-1421 -- Updated documentation

- Jenkinsfile.cd
- Jenkinsfile.ci
- wrappers/ios/Gemfile
> Updated gem cocoapods-downloader to 1.2.2

- cli/src/commands/ledger.rs
- cli/src/libindy/ledger.rs
- cli/src/main.rs
- docs/design/001-cli/README.md
- docs/how-tos/transaction-author-agreement.md
> IS-1438: CLI get list of all acceptance mechanisms

- cli/src/commands/ledger.rs
- docs/design/001-cli/README.md
- docs/how-tos/transaction-author-agreement.md
- libindy/include/indy_ledger.h
- libindy/src/api/ledger.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyLedger.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ledger/Ledger.java
- wrappers/nodejs/README.md
- wrappers/python/indy/ledger.py
- wrappers/rust/src/ledger.rs
> TAA documentation updates

- vcx/libvcx/Cargo.toml
- vcx/wrappers/java/gradle.properties
- vcx/wrappers/node/package.json
- vcx/wrappers/python3/setup.py
> IS-1442: Fixed lisenses

- Jenkinsfile.cd
- Jenkinsfile.ci
> IS-1440 -- Fix default param

- wrappers/python/indy/ledger.py
> Python: `text` parameter must be optional for build_taa

- cli/src/commands/ledger.rs
> Fixed freshness issue in CLI get_acceptance_mechanism test

- ci/indy-pool.dockerfile
- libindy/tests/ledger.rs
- libindy/tests/utils/ledger.rs
> IS-1457: Integrate TAA changes with latest Indy Node

- libindy/src/domain/anoncreds/proof_request.rs
> IS-1460 -- Add nonce validation

- vcx/libvcx/src/v3/handlers/issuance/holder.rs
- vcx/libvcx/src/v3/handlers/issuance/issuer.rs
- vcx/libvcx/src/v3/handlers/issuance/messages.rs
- vcx/libvcx/src/v3/handlers/proof_presentation/prover/messages.rs
- vcx/libvcx/src/v3/handlers/proof_presentation/prover/states.rs
- vcx/libvcx/src/v3/handlers/proof_presentation/verifier/states.rs
- vcx/libvcx/src/v3/messages/a2a/mod.rs
- vcx/libvcx/src/v3/messages/issuance/credential_ack.rs
- vcx/libvcx/src/v3/messages/issuance/mod.rs
- vcx/libvcx/src/v3/messages/proof_presentation/mod.rs
- vcx/libvcx/src/v3/messages/proof_presentation/presentation_ack.rs
> Adopt Ack message for CredentialIssuance and Presentation protocols

- cli/src/commands/ledger.rs
- cli/src/commands/pool.rs
> CLI show TAA digest

- docs/configuration.md
- libindy/src/api/pool.rs
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyPool.h
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/pool/Pool.java
- wrappers/nodejs/README.md
- wrappers/python/indy/pool.py
- wrappers/rust/src/pool.rs
> IS-1385: Improved documentation about pool opening parameters

- libindy/tests/ledger.rs
- wrappers/rust/src/logger.rs
> clippy warnings fixed

- vcx/wrappers/java/build.gradle
> CI/CD: Updated gradle properties for VCX-java to use https for maven dependencies downloading.

- wrappers/nodejs/test/anoncreds.js
> IS-1464: verifierVerifyProof returns true irrespective of value of requested predicates

- libindy/src/services/pool/request_handler.rs
> IS-1333: Generator Point description

- libindy/src/domain/anoncreds/proof.rs
- libindy/src/domain/anoncreds/proof_request.rs
- libindy/tests/anoncreds.rs
- vcx/libvcx/src/messages/proofs/proof_request.rs
> Allow omitting of attributes and predicates field in ProofRequest

- vcx/dummy-cloud-agent/Cargo.toml
- vcx/dummy-cloud-agent/src/actors/admin.rs
- vcx/dummy-cloud-agent/src/actors/agent.rs
- vcx/dummy-cloud-agent/src/actors/agent_connection.rs
- vcx/dummy-cloud-agent/src/actors/forward_agent.rs
- vcx/dummy-cloud-agent/src/actors/forward_agent_connection.rs
- vcx/dummy-cloud-agent/src/actors/mod.rs
- vcx/dummy-cloud-agent/src/actors/requester.rs
- vcx/dummy-cloud-agent/src/actors/router.rs
- vcx/dummy-cloud-agent/src/api_agent.rs
- vcx/dummy-cloud-agent/src/app.rs
- vcx/dummy-cloud-agent/src/app_admin.rs
- vcx/dummy-cloud-agent/src/domain/a2a.rs
- vcx/dummy-cloud-agent/src/domain/a2connection.rs
- vcx/dummy-cloud-agent/src/domain/config.rs
- vcx/dummy-cloud-agent/src/domain/internal_message.rs
- vcx/dummy-cloud-agent/src/domain/invite.rs
- vcx/dummy-cloud-agent/src/domain/message_type.rs
- vcx/dummy-cloud-agent/src/domain/payload.rs
- vcx/dummy-cloud-agent/src/indy/crypto.rs
- vcx/dummy-cloud-agent/src/indy/did.rs
- vcx/dummy-cloud-agent/src/indy/logger.rs
- vcx/dummy-cloud-agent/src/indy/pairwise.rs
- vcx/dummy-cloud-agent/src/indy/wallet.rs
- vcx/dummy-cloud-agent/src/indy/wallet_plugin.rs
- vcx/dummy-cloud-agent/src/main.rs
- vcx/dummy-cloud-agent/src/utils/futures.rs
- vcx/dummy-cloud-agent/src/utils/rand.rs
- vcx/dummy-cloud-agent/src/utils/tests.rs
- Added rust2018 edition to `cargo.toml`
- Align `use` statements with Rust 2018 style
> Use Rust2018 edition in vcx agency

- wrappers/ios/libindy-pod/Indy-demoTests/Test Utils/WalletUtils.m
> Indy iOS tests: Extended timeout for closing wallet

- vcx/libvcx/src/v3/handlers/connection/states.rs
> IS-1450: Aries connection acknowledgment

- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/LibVcx.java
- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/vcx/VcxApi.java
> adds vcx_version api to java wrapper

- samples/nodejs/src/gettingStarted.js
- vcx/ci/change_toml_version.py
- vcx/ci/scripts/buildnum.py
- vcx/ci/scripts/cargo-update-so
- vcx/ci/scripts/cargo-update-version
- vcx/ci/scripts/create_npm_deb.py
- vcx/ci/scripts/toml_utils.py
- vcx/ci/scripts/version_utils.py
- vcx/libvcx/scripts/provision_agent_keys.py
- vcx/wrappers/python3/demo/alice-pg.py
- vcx/wrappers/python3/demo/demo_utils.py
- vcx/wrappers/python3/demo/faber-pg.py
- vcx/wrappers/python3/demo/faber.py
- vcx/wrappers/python3/generate_docs.py
- vcx/wrappers/python3/vcx/api/credential.py
- vcx/wrappers/python3/vcx/api/credential_def.py
- vcx/wrappers/python3/vcx/api/issuer_credential.py
- wrappers/python/indy/libindy.py
> IS-1478: Fixed lgtm warnings

- samples/python/src/endorser.py
- samples/python/src/getting_started.py
- samples/python/src/txn_author_agreement.py
- samples/python/src/utils.py
> Updated Ptrhon samples to resubmit GET requests

- wrappers/java/pom.xml
Remove duplicate dependency definitions about org.json.json
> Remove duplicate dependency

- samples/java/pom.xml
- vcx/wrappers/java/build.gradle
Signed-off-by: kukgini <kukgini@gmail.com>
> Adjusted all simple JSON library versions to be the same.

- vcx/dummy-cloud-agent/README.md
- vcx/dummy-cloud-agent/docs/admin-api.md
- vcx/dummy-cloud-agent/docs/architecture.md
- vcx/dummy-cloud-agent/docs/postgres-wallet.md
- vcx/dummy-cloud-agent/src/actors/admin.rs
- vcx/dummy-cloud-agent/src/actors/agent.rs
- vcx/dummy-cloud-agent/src/actors/agent_connection.rs
- vcx/dummy-cloud-agent/src/actors/forward_agent.rs
- vcx/dummy-cloud-agent/src/actors/forward_agent_connection.rs
- vcx/dummy-cloud-agent/src/actors/router.rs
- vcx/dummy-cloud-agent/src/api_agent.rs
- vcx/dummy-cloud-agent/src/domain/a2a.rs
- vcx/dummy-cloud-agent/src/domain/key_derivation.rs
- vcx/dummy-cloud-agent/src/utils/wallet.rs
Added documentation for cloud agency plus proposing few variable renames within the agency to make things bit more consistent and clearer.
Signed-off-by: Patrik Stas <patrik.stas@absa.co.za>
> Add documentation for VCX Agency, rename variables

- Jenkinsfile.cd
> Fix CD pipeline.

- libindy/indy-utils/src/wql.rs
- libindy/indy-wallet/src/wallet.rs
- libindy/src/services/anoncreds/prover.rs
- libindy/tests/anoncreds_demos.rs
> IS-1522: Libindy fails in case ProofRequest contains restrictions as empty array

- vcx/libvcx/src/connection.rs
- vcx/libvcx/src/v3/handlers/connection/agent.rs
> Fixed VCX compatibility between 1.0 and aries

- vcx/libvcx/src/messages/get_message.rs
- vcx/libvcx/src/v3/mod.rs
> Bugfix/vcx cred offer serialization in case aries Issuer <-> old Prover that uses `download_messages` function

- vcx/libvcx/src/connection.rs
- vcx/libvcx/src/messages/create_key.rs
- vcx/wrappers/python3/demo/alice.py
- vcx/wrappers/python3/demo/faber.py
> IS-1519: VCX protocols compatibility: Connection fix for evernym agency

- vcx/libvcx/src/utils/libindy/wallet.rs
- vcx/libvcx/src/v3/handlers/connection/states.rs
- vcx/libvcx/src/v3/messages/attachment.rs
- vcx/libvcx/src/v3/messages/connection/did_doc.rs
- vcx/libvcx/src/v3/messages/issuance/credential.rs
- vcx/libvcx/src/v3/messages/issuance/credential_offer.rs
- vcx/libvcx/src/v3/messages/issuance/credential_request.rs
- vcx/libvcx/src/v3/messages/proof_presentation/presentation.rs
- vcx/libvcx/src/v3/messages/proof_presentation/presentation_request.rs
- vcx/wrappers/python3/demo/faber.py
- vcx/wrappers/python3/demo/requirements.txt
> IS-1527: LibVCX compatibility with StreetCred

- wrappers/python/tests/anoncreds/test_proof_predicates.py
Python wrapper test demonstrating all supported predicate types
Signed-off-by: sklump <srklump@hotmail.com>
> python wrapper test for <, <=, >=, > predicate types

- docs/getting-started/indy-walkthrough.md
Signed-off-by: rakaar <rka87338@gmail.com>
> Corrected Minor syntax error in docs

- README.md
Added a step to install dependent libraries.
> Refine installation guide for MacOS

- vcx/libvcx/src/api/wallet.rs
- vcx/libvcx/src/messages/agent_utils.rs
- vcx/wrappers/node/package.json
- vcx/wrappers/python3/demo/alternate_wallet_path.py
> adds custom wallet path test

- libindy/indy-utils/src/ctypes.rs
- libindy/src/api/logger.rs
- libindy/src/utils/logger.rs
- libindy/tests/logger.rs
- libindy/tests/logger_lvl.rs
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibIndy.java
- wrappers/rust/indy-sys/src/logger.rs
This PR optimizes libindy and Java wrapper behavior in scope of #2183
> [gh-2183] Fix libindy and java wrapper.

- libindy/src/commands/did.rs
- libindy/tests/logger_lvl.rs
Signed-off-by: Sergey Khoroshavin <sergey.khoroshavin@dsr-corporation.com>
> Reduce log level of messages in did.rs

- vcx/libvcx/src/api/disclosed_proof.rs
- vcx/libvcx/src/api/proof.rs
- vcx/libvcx/src/api/schema.rs
- vcx/libvcx/src/v3/handlers/proof_presentation/prover/states.rs
I've been reading doc comments as I study the code. I just improved a few as I went along. This PR is not particularly urgent, but it would improve the code's readability a bit. I will probably submit similar small changes on an ongoing basis.
> minor fixes for typos and documentation

- libindy/indy-wallet/src/lib.rs
> Fix O(n) wallet collection traversing

- libindy/src/commands/did.rs
- libindy/tests/did.rs
- libindy/tests/utils/did.rs
https://github.com/hyperledger/indy-sdk/blob/master/wrappers/nodejs/README.md says that listMyDidsWithMeta API does not return tempVerkey field, but the current implementation does. I follow the current implementation.
> IS-1561: performance improvement of listMyDidsWithMeta

- libindy/Cargo.toml
- libindy/src/commands/metrics.rs
- libindy/src/commands/mod.rs
- libindy/src/lib.rs
- libindy/src/services/metrics/command_index.rs
- libindy/src/services/metrics/mod.rs
- libindy/src/services/mod.rs
- libindy/tests/metrics.rs
- wrappers/rust/tests/metrics.rs
> [VE-2045][3]: add command metrics

- CHANGELOG.md
- README.md
- Specs/libindy/1.16.0/libindy.podspec.json
- cli/Cargo.lock
- cli/Cargo.toml
- cli/debian/changelog
- docs/migration-guides/migration-guide-1.15.0-1.16.0.md
- libindy/Cargo.lock
- libindy/Cargo.toml
- libindy/debian/changelog
- libnullpay/Cargo.toml
- libnullpay/debian/changelog
- vcx/README.md
- vcx/docs/migration-guide-0.8.x-0.9.0.md
- vcx/libvcx/Cargo.lock
- vcx/libvcx/Cargo.toml
- vcx/libvcx/debian/changelog
- vcx/wrappers/java/build.gradle
- vcx/wrappers/node/package.json
- vcx/wrappers/python3/demo/requirements.txt
- vcx/wrappers/python3/setup.py
- wrappers/java/pom.xml
- wrappers/nodejs/package.json
- wrappers/python/setup.py
- wrappers/rust/Cargo.toml
- wrappers/rust/indy-sys/Cargo.toml
Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>
Version numbers are updated, release notes are still t.b.d.
> Bump version numbers for 1.16.0 sdk release

- Jenkinsfile.cd
- Jenkinsfile.ci
- wrappers/ios/README.md
Enhanced documentation about downgrading Rust for iOS
> Enhanced documentation about downgrading Rust for iOS 

- Jenkinsfile.cd
- Jenkinsfile.ci
- vcx/libvcx/build_scripts/android/vcx/build.nondocker.sh
- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/LibVcx.java
- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/connection/ConnectionApi.java
- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/credential/CredentialApi.java
- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/issuer/IssuerApi.java
- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/proof/DisclosedProofApi.java
- vcx/wrappers/java/src/main/java/com/evernym/sdk/vcx/proof/ProofApi.java
- wrappers/ios/README.md
- wrappers/ios/libindy-pod/Indy/Wrapper/IndyErrors.h
Alternate PR that cherry-picks commits to avoid the DCO issue
> Updates to iOS build for sdk release 1.16.0

- ci/indy-pool.dockerfile
> Pin versions of dependencies Indy Node and Plenum.

- cli/src/commands/ledger.rs
- cli/src/commands/mod.rs
- cli/src/libindy/ledger.rs
- cli/src/main.rs
- libindy/include/indy_ledger.h
- libindy/src/api/ledger.rs
- libindy/src/commands/ledger.rs
- libindy/src/domain/ledger/constants.rs
- libindy/src/domain/ledger/ledgers_freeze.rs
- libindy/src/domain/ledger/mod.rs
- libindy/src/services/ledger/mod.rs
- libindy/src/services/metrics/command_metrics.rs
- libindy/tests/ledger.rs
- libindy/tests/utils/ledger.rs
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/LibIndy.java
- wrappers/java/src/main/java/org/hyperledger/indy/sdk/ledger/Ledger.java
- wrappers/java/src/test/java/org/hyperledger/indy/sdk/ledger/GetFrozenLedgersTest.java
- wrappers/nodejs/src/index.js
- wrappers/nodejs/src/indy.cc
- wrappers/nodejs/test/ledger.js
- wrappers/python/indy/ledger.py
- wrappers/python/tests/ledger/test_build_freeze_ledgers_request.py
- wrappers/python/tests/ledger/test_build_get_frozen_ledgers_request.py
- wrappers/python/tests/ledger/test_build_ledgers_freeze_request.py
- wrappers/rust/indy-sys/src/ledger.rs
- wrappers/rust/src/ledger.rs
- wrappers/rust/tests/ledger.rs
Signed-off-by: Anton Denishchenko <anton.denishchenko@dsr-corporation.com>
> UP-42: Add API calls for frozen ledgers

- libindy/Cargo.lock
Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>
> Fix Cargo.lock to match main branch

- experimental/plugins/postgres_storage/Cargo.toml
- experimental/plugins/postgres_storage/src/postgres_storage.rs
> percent encoding of passwords in Postgres Plug-In

- .github/settings.yml
Signed-off-by: Wade Barnes <wade@neoterictech.ca>
> Allow merge commits

- experimental/plugins/postgres_storage/src/postgres_storage.rs
Signed-off-by: pmccabensds <patrick.mccabe@novascotia.ca>
> encode postgres account name to work with azure to address Issue #2388

- experimental/plugins/postgres_storage/src/postgres_storage.rs
Signed-off-by: Ian Costanzo <ian@anon-solutions.ca>
If wallet db already exists, checks for metadata before deciding that "wallet already exists".
> Update postgres check for existing database/schema

- docs/getting-started/getting-started.dockerfile
- docs/getting-started/getting-started.ipynb
Bumped ubuntu version to 18.04
changed to pip packages to use `notebook`  instead of `ipython-notebook`
also formatting
> Fixing #2379 

- samples/java/README.md
- samples/java/pom.xml
- samples/java/src/main/java/Anoncreds.java
- samples/java/src/main/java/AnoncredsRevocation.java
- samples/java/src/main/java/Crypto.java
- samples/java/src/main/java/Endorser.java
- samples/java/src/main/java/Ledger.java
signed-off-by: Thomas Diesler <tdiesler@redhat.com>
> [#2468] Allow java samples to run individually & polish sample docs

- .github/workflows/main.yml
Signed-off-by: Wade Barnes <wade@neoterictech.ca>
> Update the version of Rust used in the workflows.

- libindy/mac.build.sh
signed-off-by: Thomas Diesler <tdiesler@redhat.com>
> [#2471] Failed to find OpenSSL development headers on MacOS

- wrappers/nodejs/README.md
Signed-off-by: Mujeebullah Kalwar <mujeebkalwar.mk@gmail.com>
> Fixed Docs Link in README.md
